// ==========================================
// CONFIGURATION
// ==========================================
const DEFAULT_DATE = new Date().toLocaleDateString('en-CA');

// Global State
let ALL_GAMES_DATA = []; 

// ==========================================
// 1. MAIN APP LOGIC
// ==========================================
// --- LOCAL ODDS MATCHER ---

async function fetchLocalOdds() {
    try {
        console.log("Checking local odds file generated by Python...");
        // Ensure this path matches where the Python script saves the file
        const response = await fetch('data/odds.json?v=' + new Date().getTime()); 
        
        if (response.ok) {
            const fileData = await response.json();
            console.log(`✅ Loaded ${fileData.game_count} odds from server (Last updated: ${new Date(fileData.last_updated).toLocaleTimeString()})`);
            return fileData.odds;
        } else {
            console.log("⚠️ data/odds.json exists but returned an error.");
            return null;
        }
    } catch (e) {
        console.log("No local odds.json file found. Ensure the Python cron job is running.");
        return null; 
    }
}
async function init(dateToFetch) {
    console.log(`🚀 Starting App. Fetching games for: ${dateToFetch}`);
    
    const container = document.getElementById('games-container');
    const datePicker = document.getElementById('date-picker');
    
    // Reset State
    ALL_GAMES_DATA = [];
    if (datePicker) datePicker.value = dateToFetch;

    if (container) {
        container.innerHTML = `
            <div class="col-12 text-center mt-5 pt-5">
                <div class="spinner-border text-primary" role="status"></div>
                <p class="mt-3 text-muted" id="loading-text">Loading Schedule...</p>
            </div>`;
    }
    
    const MLB_API_URL = `https://statsapi.mlb.com/api/v1/schedule?sportId=1&date=${dateToFetch}&hydrate=linescore,venue,probablePitcher,lineups`;
    
    try {
        let stadiumResponse = await fetch('data/stadiums.json');
        if (!stadiumResponse.ok) stadiumResponse = await fetch('stadiums.json');
        const stadiums = await stadiumResponse.json();

        const scheduleResponse = await fetch(MLB_API_URL);
        const scheduleData = await scheduleResponse.json();

        if (scheduleData.totalGames === 0) {
            container.innerHTML = `
                <div class="col-12 text-center mt-5">
                    <div class="alert alert-light shadow-sm py-4">
                        <h4 class="text-muted">No games scheduled for ${dateToFetch}</h4>
                        <p class="small text-muted mb-0">Spring Training starts Feb 20!</p>
                    </div>
                </div>`;
            return;
        }

        const rawGames = scheduleData.dates[0].games;
        const totalGames = rawGames.length;

        // --- FETCH ODDS FROM LOCAL SERVER ONLY ---
        let dailyOddsData = await fetchLocalOdds();
        
        // Loop through games
        for (let i = 0; i < totalGames; i++) {
            const game = rawGames[i];
            document.getElementById('loading-text').innerText = `Analyzing game ${i+1} of ${totalGames}...`;

            const venueId = game.venue.id;
            const stadium = stadiums.find(s => s.id === venueId);
            
            let weatherData = null;
            let windData = null;
            let isRoofClosed = false;

            if (stadium) {
                weatherData = await fetchGameWeather(stadium.lat, stadium.lon, game.gameDate);
                
                if (weatherData.status !== "too_early" && weatherData.temp !== '--') {
                    windData = calculateWind(weatherData.windDir, stadium.bearing);
                    
                    if (stadium.dome) isRoofClosed = true;
                    else if (stadium.roof) {
                        if (weatherData.maxPrecipChance > 30 || weatherData.temp < 50 || weatherData.temp > 95) isRoofClosed = true;
                    }
                    if (isRoofClosed) {
                        windData = { text: "Roof Closed", cssClass: "bg-secondary text-white", arrow: "" };
                        weatherData.windSpeed = 0; 
                    }
                }
            }

            // --- NEW: MATCH THE ODDS DATA TO THIS SPECIFIC GAME ---
            let gameOdds = null;
            if (dailyOddsData) {
                gameOdds = dailyOddsData.find(o => 
                    o.home_team === game.teams.home.team.name && 
                    o.away_team === game.teams.away.team.name
                );
            }

            ALL_GAMES_DATA.push({
                gameRaw: game,
                stadium: stadium,
                weather: weatherData,
                wind: windData,
                roof: isRoofClosed,
                odds: gameOdds
            });
        }

        renderGames();

    } catch (error) {
        console.error("❌ ERROR:", error);
        container.innerHTML = `<div class="col-12 text-center mt-5"><div class="alert alert-danger">${error.message}</div></div>`;
    }
}

// ==========================================
// 2. RENDERING ENGINE
// ==========================================

function renderGames() {
    const container = document.getElementById('games-container');
    container.innerHTML = '';

    const searchText = document.getElementById('team-search').value.toLowerCase();
    const sortMode = document.getElementById('sort-filter').value;
    const risksOnly = document.getElementById('risk-only').checked;

    let filteredGames = ALL_GAMES_DATA.filter(item => {
        const g = item.gameRaw;
        const teams = (g.teams.away.team.name + " " + g.teams.home.team.name).toLowerCase();
        
        // 1. Search Filter
        if (!teams.includes(searchText)) return false;

        // 2. Risk Filter (UPDATED: RAIN ONLY)
        if (risksOnly) {
            // If no weather data, hide it
            if (!item.weather || item.weather.temp === '--') return false; 
            
            // If roof is closed, it's never a risk
            if (item.roof) return false;

            // STRICT RULE: Only show if Rain >= 30%
            if (item.weather.maxPrecipChance < 30) return false;
        }
        return true;
    });

    // 3. Sorting
    filteredGames.sort((a, b) => {
        const aValid = a.weather && a.weather.temp !== '--';
        const bValid = b.weather && b.weather.temp !== '--';
        if (!aValid && bValid) return 1;
        if (aValid && !bValid) return -1;

        if (sortMode === 'wind') return (b.weather?.windSpeed || 0) - (a.weather?.windSpeed || 0);
        if (sortMode === 'rain') return (b.weather?.maxPrecipChance || 0) - (a.weather?.maxPrecipChance || 0);
        if (sortMode === 'temp') return (b.weather?.temp || 0) - (a.weather?.temp || 0);
        if (sortMode === 'humidity') return (b.weather?.humidity || 0) - (a.weather?.humidity || 0);
        
        return new Date(a.gameRaw.gameDate) - new Date(b.gameRaw.gameDate);
    });

    if (filteredGames.length === 0) {
        container.innerHTML = `<div class="col-12 text-center py-5 text-muted">No games match your filters.</div>`;
        return;
    }

    filteredGames.forEach(item => {
        container.appendChild(createGameCard(item));
    });
}

function createGameCard(data) {
    const game = data.gameRaw;
    const stadium = data.stadium;
    const weather = data.weather;
    const windInfo = data.wind;
    const isRoofClosed = data.roof;

    // --- 1. Risk Border Logic ---
    let borderClass = ""; 
    if (weather && !isRoofClosed) {
        if (weather.isThunderstorm) borderClass = "border-danger border-3"; 
        else if (weather.maxPrecipChance >= 70) borderClass = "border-danger border-3"; 
        else if (weather.maxPrecipChance >= 30) borderClass = "border-warning border-3"; 
    }

    // --- 2. Animated Background Logic ---
    let bgClass = "bg-weather-sunny"; 
    if (isRoofClosed) {
        bgClass = "bg-weather-roof";
    } else if (weather) {
        if (weather.isThunderstorm) bgClass = "bg-weather-storm";
        else if (weather.isSnow) bgClass = "bg-weather-snow";
        else if (weather.maxPrecipChance >= 50) bgClass = "bg-weather-rain";
        else if (weather.maxPrecipChance >= 20) bgClass = "bg-weather-cloudy";
        else if (weather.temp >= 90) bgClass = "bg-weather-sunny"; 
    }

    const gameCard = document.createElement('div');
    gameCard.className = 'col-md-6 col-lg-4 animate-card';

    // Teams & Pitchers
    const awayAbbr = getTeamAbbr(game.teams.away.team.name);
    const homeAbbr = getTeamAbbr(game.teams.home.team.name);
    const awayId = game.teams.away.team.id;
    const homeId = game.teams.home.team.id;
    const awayName = game.teams.away.team.name;
    const homeName = game.teams.home.team.name;
    const awayLogo = `https://www.mlbstatic.com/team-logos/team-cap-on-light/${awayId}.svg`;
    const homeLogo = `https://www.mlbstatic.com/team-logos/team-cap-on-light/${homeId}.svg`;
    const gameTime = new Date(game.gameDate).toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'});

    const awayPitcher = game.teams.away.probablePitcher?.fullName || "TBD";
    const homePitcher = game.teams.home.probablePitcher?.fullName || "TBD";

    // --- 3. LINEUPS LOGIC ---
    const lineupAway = game.lineups?.awayPlayers || [];
    const lineupHome = game.lineups?.homePlayers || [];

    let awayLineupHtml = '';
    if (lineupAway.length > 0) {
        const list = lineupAway.map((p) => `<li>${p.fullName}</li>`).join('');
        const collapseId = `lineup-away-${game.gamePk}`;
        awayLineupHtml = `
            <div class="mt-2">
                <a href="#${collapseId}" data-bs-toggle="collapse" class="badge bg-primary text-white text-decoration-none" style="font-size: 0.65rem;">📋 View Lineup</a>
                <div class="collapse mt-2 text-start bg-light rounded p-2 border" id="${collapseId}">
                    <ol class="mb-0 ps-3 text-muted fw-bold" style="font-size: 0.65rem; line-height: 1.4;">${list}</ol>
                </div>
            </div>`;
    }

    let homeLineupHtml = '';
    if (lineupHome.length > 0) {
        const list = lineupHome.map((p) => `<li>${
// ==========================================
// 3. LISTENERS
// ==========================================

document.addEventListener('DOMContentLoaded', () => {
    // 1. Start App
    init(DEFAULT_DATE);

    // 2. Filter Listeners
    const searchInput = document.getElementById('team-search');
    const sortSelect = document.getElementById('sort-filter');
    const riskToggle = document.getElementById('risk-only');
    
    if(searchInput) searchInput.addEventListener('input', renderGames);
    if(sortSelect) sortSelect.addEventListener('change', renderGames);
    if(riskToggle) riskToggle.addEventListener('change', renderGames);

    // 3. Date Picker Listener (UPDATED)
    const datePicker = document.getElementById('date-picker');
    
    if (datePicker) {
        // Set initial value
        datePicker.value = DEFAULT_DATE;

        // Listen for changes
        datePicker.addEventListener('change', (e) => {
            if (e.target.value) {
                // Close keyboard on mobile
                e.target.blur(); 
                // Fetch new games
                init(e.target.value);
            }
        });
    }
});

// ==========================================
// 4. HELPER FUNCTIONS
// ==========================================
function getWindArrowEmoji(direction) {
    // 1. Handle missing data
    if (direction === null || direction === undefined) return "💨";

    // 2. Handle Degrees (if the API sends a number like 180, 270)
    if (typeof direction === 'number') {
        const val = Math.floor((direction / 22.5) + 0.5);
        const arr = ["N", "NNE", "NE", "ENE", "E", "ESE", "SE", "SSE", "S", "SSW", "SW", "WSW", "W", "WNW", "NW", "NNW"];
        direction = arr[(val % 16)];
    }

    // 3. Map Compass String to Arrow Emoji
    const map = {
        "N": "⬇️",   "NNE": "⬇️", "NE": "↙️",  "ENE": "↙️", // Wind from North flows Down/South
        "E": "⬅️",   "ESE": "⬅️", "SE": "↖️",  "SSE": "↖️", // Wind from East flows Left/West
        "S": "⬆️",   "SSW": "⬆️", "SW": "↗️",  "WSW": "↗️", // Wind from South flows Up/North
        "W": "➡️",   "WNW": "➡️", "NW": "↘️",  "NNW": "↘️"  // Wind from West flows Right/East
    };

    // Note: Weather arrows usually point "Where the wind is going", 
    // so a North wind (From North) points Down (South).
    
    return map[direction.toUpperCase()] || "💨";
}

// Helper: Get Standard 3-Letter Code
function getTeamAbbr(teamName) {
    const map = {
        // Shared Cities (Must be 3 letters)
        "Yankees": "NYY", "Mets": "NYM",
        "Cubs": "CHC", "White Sox": "CWS",
        "Dodgers": "LAD", "Angels": "LAA",
        
        // The Rest (Standard Scoreboard Codes)
        "Diamondbacks": "ARI", "Braves": "ATL", "Orioles": "BAL", "Red Sox": "BOS",
        "Reds": "CIN", "Guardians": "CLE", "Rockies": "COL", "Tigers": "DET",
        "Astros": "HOU", "Royals": "KC",  "Marlins": "MIA", "Brewers": "MIL",
        "Twins": "MIN", "Athletics": "OAK", "Phillies": "PHI", "Pirates": "PIT",
        "Padres": "SD",  "Giants": "SF",  "Mariners": "SEA", "Cardinals": "STL",
        "Rays": "TB",   "Rangers": "TEX", "Blue Jays": "TOR", "Nationals": "WSH"
    };

    // Find key match
    const key = Object.keys(map).find(k => teamName.includes(k));
    return key ? map[key] : "MLB"; // Default
}

window.showRadar = function(url, venueName) {
    const modalTitle = document.querySelector('#radarModal .modal-title');
    const iframe = document.getElementById('radarFrame');
    if(modalTitle) modalTitle.innerText = `Radar: ${venueName}`;
    if(iframe) iframe.src = url;
    const myModal = new bootstrap.Modal(document.getElementById('radarModal'));
    myModal.show();
}

function generateMatchupAnalysis(weather, windInfo, isRoofClosed) {
    if (isRoofClosed) return "Roof closed. Controlled environment with zero weather impact.";

    let notes = [];

    // 1. Safety Hazards (Lightning & Snow)
    if (weather.isThunderstorm) {
        notes.push("⚡ <b>Lightning Risk:</b> Thunderstorms detected. Mandatory 30-minute safety delays are likely.");
    }
    if (weather.isSnow) {
        notes.push("❄️ <b>Snow Risk:</b> Low visibility and slippery field conditions could delay play.");
    }

    // 2. Rain Analysis
    if (weather.maxPrecipChance >= 70) {
        notes.push("🌧️ <b>Rainout Risk:</b> High probability of postponement.");
    } else if (weather.maxPrecipChance >= 30) {
        notes.push("☔ <b>Delay Risk:</b> Scattered showers could interrupt play.");
    }

    // 3. Humidity Analysis
    if (weather.humidity <= 30) {
        notes.push("🌵 <b>Dry Air (<30%):</b> Sharp breaking balls (Pitcher Adv), but the ball travels up to 4.5ft farther (Hitter Adv).");
    } else if (weather.humidity >= 70) {
        notes.push("💧 <b>High Humidity (>70%):</b> Breaking balls hang/flatten (Hitter Adv), but the ball travels shorter distances (Pitcher Adv).");
    }

    // 4. Temp Analysis
    if (weather.temp >= 85) {
        notes.push("🔥 <b>Hitter Friendly:</b> High temps reduce air density, helping fly balls carry.");
    } else if (weather.temp <= 50) {
        notes.push("❄️ <b>Pitcher Friendly:</b> Cold, dense air suppresses ball flight and scoring.");
    }

    // 5. Wind Analysis
    if (weather.windSpeed >= 8) {
        const dir = windInfo.text;
        if (dir.includes("Blowing OUT")) notes.push("🚀 <b>Home Runs:</b> Strong wind blowing out creates ideal hitting conditions.");
        else if (dir.includes("Blowing IN")) notes.push("🛑 <b>Suppressed:</b> Wind blowing in will knock down fly balls. Advantage pitchers.");
        else if (dir.includes("Out to Right")) notes.push("↗️ <b>Lefty Advantage:</b> Wind blowing out to Right Field favors <b>Left-Handed</b> power.");
        else if (dir.includes("Out to Left")) notes.push("↖️ <b>Righty Advantage:</b> Wind blowing out to Left Field favors <b>Right-Handed</b> power.");
        else if (dir.includes("In from Right")) notes.push("📉 <b>Lefty Nightmare:</b> Wind blowing in from Right knocks down Lefty power.");
        else if (dir.includes("In from Left")) notes.push("📉 <b>Righty Nightmare:</b> Wind blowing in from Left knocks down Righty power.");
        else if (dir.includes("Cross")) notes.push("↔️ <b>Tricky:</b> Crosswinds may affect outfield defense and breaking balls.");
    }

    if (notes.length === 0) return "✅ <b>Neutral:</b> Fair weather conditions. No significant advantage.";
    return notes.join("<br>");
}
async function fetchGameWeather(lat, lon, gameDateIso) {
    const dateStr = gameDateIso.split('T')[0];
    const today = new Date().toLocaleDateString('en-CA'); 
    const isHistorical = dateStr < today; 
    const daysDiff = (new Date(dateStr) - new Date(today)) / (1000 * 60 * 60 * 24);

    if (!isHistorical && daysDiff > 16) return { status: "too_early", temp: '--' };

    let url = "";
    if (isHistorical || dateStr === "2024-09-25") {
         url = `https://archive-api.open-meteo.com/v1/archive?latitude=${lat}&longitude=${lon}&start_date=${dateStr}&end_date=${dateStr}&hourly=temperature_2m,relative_humidity_2m,precipitation,weather_code,wind_speed_10m,wind_direction_10m&temperature_unit=fahrenheit&wind_speed_unit=mph&precipitation_unit=inch&timezone=auto`;
    } 
    else if (daysDiff <= 3) {
         url = `https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&hourly=temperature_2m,relative_humidity_2m,precipitation_probability,weather_code,wind_speed_10m,wind_direction_10m&temperature_unit=fahrenheit&wind_speed_unit=mph&precipitation_unit=inch&timezone=auto&start_date=${dateStr}&end_date=${dateStr}`;
    }
    else {
         url = `https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&hourly=temperature_2m,relative_humidity_2m,precipitation_probability,weather_code,wind_speed_10m,wind_direction_10m&models=gfs_seamless&temperature_unit=fahrenheit&wind_speed_unit=mph&precipitation_unit=inch&timezone=auto&start_date=${dateStr}&end_date=${dateStr}`;
    }

    try {
        const response = await fetch(url);
        if (!response.ok) {
            if (response.status === 400) return { status: "too_early", temp: '--' };
            return { temp: '--', hourly: [] };
        }
        const data = await response.json();
        const gameHour = new Date(gameDateIso).getHours();
        
        const normalizePrecip = (index) => {
            let chance = 0;
            if (data.hourly.precipitation_probability) chance = data.hourly.precipitation_probability[index];
            else if (data.hourly.precipitation) {
                const amount = data.hourly.precipitation[index];
                if (amount >= 0.10) chance = 80;      
                else if (amount >= 0.05) chance = 60; 
                else if (amount >= 0.01) chance = 30; 
            }
            return chance;
        };

        const hourlySlice = [];
        let maxChanceInWindow = 0;
        let isGameThunderstorm = false;
        let isGameSnow = false; // NEW FLAG

        for (let i = gameHour - 1; i <= gameHour + 4; i++) {
            if (i >= 0 && i < 24) {
                let chance = normalizePrecip(i);
                
                const code = data.hourly.weather_code[i];
                
                // Thunderstorm Codes: 95, 96, 99
                const isHourThunderstorm = (code === 95 || code === 96 || code === 99);
                
                // Snow Codes: 71, 73, 75 (Snow), 77 (Grains), 85, 86 (Showers)
                const isHourSnow = (code === 71 || code === 73 || code === 75 || code === 77 || code === 85 || code === 86);

                if (isHourThunderstorm) isGameThunderstorm = true;
                if (isHourSnow) isGameSnow = true;

                if (i >= gameHour && i <= gameHour + 3 && chance > maxChanceInWindow) maxChanceInWindow = chance;
                
               hourlySlice.push({ 
                    hour: i, 
                    temp: Math.round(data.hourly.temperature_2m[i]), // <--- ADD THIS LINE
                    precipChance: chance,
                    isThunderstorm: isHourThunderstorm,
                    isSnow: isHourSnow 
                });
            }
        }

        return {
            status: "ok",
            temp: Math.round(data.hourly.temperature_2m[gameHour]),
            humidity: Math.round(data.hourly.relative_humidity_2m[gameHour]),
            maxPrecipChance: maxChanceInWindow, 
            isThunderstorm: isGameThunderstorm,
            isSnow: isGameSnow, // Pass flag to main logic
            windSpeed: Math.round(data.hourly.wind_speed_10m[gameHour]),
            windDir: data.hourly.wind_direction_10m[gameHour],
            hourly: hourlySlice
        };
    } catch (e) {
        console.error("⚠️ Weather fetch failed:", e);
        return { temp: '--', hourly: [] };
    }
}
function calculateWind(windDirection, stadiumBearing) {
    let diff = (windDirection - stadiumBearing + 360) % 360;
    if (diff >= 337.5 || diff < 22.5) return { text: "Blowing IN", cssClass: "bg-in", arrow: "⬇" };
    if (diff >= 22.5 && diff < 67.5) return { text: "In from Right", cssClass: "bg-in", arrow: "↙" };
    if (diff >= 67.5 && diff < 112.5) return { text: "Cross (R to L)", cssClass: "bg-cross", arrow: "⬅" };
    if (diff >= 112.5 && diff < 157.5) return { text: "Out to Left", cssClass: "bg-out", arrow: "↖" };
    if (diff >= 157.5 && diff < 202.5) return { text: "Blowing OUT", cssClass: "bg-out", arrow: "⬆" };
    if (diff >= 202.5 && diff < 247.5) return { text: "Out to Right", cssClass: "bg-out", arrow: "↗" };
    if (diff >= 247.5 && diff < 292.5) return { text: "Cross (L to R)", cssClass: "bg-cross", arrow: "➡" };
    return { text: "In from Left", cssClass: "bg-in", arrow: "↘" };
}
window.shareGameTweet = function(encodedData) {
    const data = JSON.parse(decodeURIComponent(encodedData));
    const g = data.gameRaw;
    const w = data.weather;
    const s = data.stadium;
    const wind = data.wind;

    const away = g.teams.away.team.name;
    const home = g.teams.home.team.name;
    const venue = g.venue.name;

    let tweet = "";

    // --- 1. DETECT MODE ---
    const isHazard = w.maxPrecipChance >= 30 || w.isThunderstorm || w.isSnow;
    const isHitterFriendly = w.temp >= 85 || (w.windSpeed >= 10 && wind.text.includes("OUT"));
    const isPitcherFriendly = w.temp <= 50 || (w.windSpeed >= 10 && wind.text.includes("IN"));

    // --- 2. BUILD HEADER ---
    if (isHazard) {
        tweet += `⚠️ WEATHER ALERT: ${away} @ ${home}\n`;
        tweet += `🏟️ ${venue}\n\n`;
        
        // Hazard Line
        if (w.isThunderstorm) tweet += `⚡ LIGHTNING RISK DETECTED\n`;
        else if (w.isSnow) tweet += `❄️ SNOW RISK DETECTED\n`;
        else tweet += `☔ RAIN DELAY RISK (${w.maxPrecipChance}%)\n`;
    } else {
        tweet += `⚾ ${away} @ ${home}\n`;
        tweet += `🏟️ ${venue}\n\n`;
    }

    // --- 3. CONDITIONS ---
    tweet += `🌡️ Temp: ${w.temp}°F\n`;
    tweet += `💧 Hum: ${w.humidity}%\n`;
    tweet += `💨 Wind: ${w.windSpeed}mph (${wind.text} ${wind.arrow})\n`;
    
    // Only show Rain % if it's not a hazard (hazards already showed it at top)
    if (!isHazard) {
        tweet += `☔ Rain: ${w.maxPrecipChance}%\n`;
    }

    // --- 4. SMART ANALYSIS ---
    tweet += `\n`;
    if (isHitterFriendly) {
        tweet += `🔥 IMPACT: Hitter Friendly! Ball carrying farther.\n`;
    } else if (isPitcherFriendly) {
        tweet += `❄️ IMPACT: Pitcher Friendly! Air density suppressing runs.\n`;
    } else if (w.humidity <= 30) {
        tweet += `🌵 IMPACT: Dry Air! Breaking balls sharp, but fly balls carry.\n`;
    }

    // --- 5. FOOTER ---
    tweet += `\n🔗 https://weathermlb.com\n#MLB #FantasyBaseball`;

    // --- 6. LAUNCH ---
    const twitterUrl = `https://twitter.com/intent/tweet?text=${encodeURIComponent(tweet)}`;
    window.open(twitterUrl, '_blank');
}

function generateDailyReport() {
    if (ALL_GAMES_DATA.length === 0) {
        alert("No games data available to report!");
        return;
    }

    // 1. Sort games by time (Earliest first)
    const sortedGames = [...ALL_GAMES_DATA].sort((a, b) => 
        new Date(a.gameRaw.gameDate) - new Date(b.gameRaw.gameDate)
    );

    // 2. Define Limits
    const MAX_TWEET_LENGTH = 260; 
    const today = new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
    
    // 3. Generate Compressed Lines
    let allLines = [];
    sortedGames.forEach(game => {
        const teams = game.gameRaw.teams;
        const w = game.weather; // 'w' matches your individual tweet variable
        
        // TEAMS
        const away = getTeamAbbr(teams.away.team.name);
        const home = getTeamAbbr(teams.home.team.name);
        
        // WIND ARROW
        // Your individual tweet uses 'wind.arrow'. 
        // We try to access that first. If it's not stored in 'game', 
        // we fall back to our helper using 'w.windDirection'.
        let arrow = "💨";
        if (game.wind && game.wind.arrow) {
             arrow = game.wind.arrow;
        } else {
             arrow = getWindArrowEmoji(game.windDirection);
        }

        // VALUES (Matches your individual tweet logic)
        // Rain: Use 'maxPrecipChance'
        const rain = Math.round(Number(w.maxPrecipChance) || 0);
        const temp = Math.round(Number(w.temp) || 0);
        const windSpd = Math.round(Number(w.windSpeed) || 0);

        // FORMAT: DET@NYY:🌧️0%🌡️72°💨9mph
        // Note: Using 'arrow' variable we just set
        const line = `${away}@${home}:🌧️${rain}%🌡️${temp}°${arrow}${windSpd}mph`;
        allLines.push(line);
    });

    // 4. Build the Thread
    let tweets = [];
    // Header for Tweet 1
    let currentTweet = `⚾MLB Weather•${today} (1/X)\n\n`; 

    allLines.forEach((line) => {
        // Check if adding this line exceeds limit
        if ((currentTweet.length + line.length + 1) > MAX_TWEET_LENGTH) {
            tweets.push(currentTweet); 
            // Header for Tweet 2, 3, etc.
            currentTweet = `(2/X) Continued...\n\n`; 
        }
        currentTweet += line + "\n";
    });

    // 5. Add Footer to the LAST tweet
    currentTweet += `\nMore details: https://weathermlb.com\n#MLB #BaseballWeather`;
    tweets.push(currentTweet);

    // 6. Format Final Text for the Box
    const finalOutput = tweets.map((t, i) => `--- TWEET ${i+1} ---\n${t}\n`).join("\n");

    // 7. POPULATE MODAL
    const textArea = document.getElementById('tweet-text');
    const twitterLink = document.getElementById('twitter-link');
    
    if (textArea) {
        textArea.value = finalOutput;

        // Update "Open X" Button
        // Pre-fill only the first tweet
        if (twitterLink && tweets.length > 0) {
            const firstTweetBody = tweets[0]; 
            const twitterUrl = `https://twitter.com/intent/tweet?text=${encodeURIComponent(firstTweetBody)}`;
            twitterLink.href = twitterUrl;
        }
        
        // Show Modal (Bootstrap)
        const modalElement = document.getElementById('tweetModal');
        if (modalElement && typeof bootstrap !== 'undefined') {
            const modal = new bootstrap.Modal(modalElement);
            modal.show();
        } else {
             // Fallback if modal fails
             alert("Report generated (Modal not found):\n\n" + finalOutput);
        }
    }
}
