// ==========================================
// CONFIGURATION
// ==========================================
const DEFAULT_DATE = new Date().toLocaleDateString('en-CA');

// Global State
let ALL_GAMES_DATA = []; 

// ==========================================
// 1. MAIN APP LOGIC
// ==========================================
// --- LOCAL ODDS MATCHER ---

async function fetchLocalOdds() {
    try {
        console.log("Checking local odds file generated by Python...");
        // Ensure this path matches where the Python script saves the file
        const response = await fetch('data/odds.json?v=' + new Date().getTime()); 
        
        if (response.ok) {
            const fileData = await response.json();
            console.log(`✅ Loaded ${fileData.game_count} odds from server (Last updated: ${new Date(fileData.last_updated).toLocaleTimeString()})`);
            return fileData.odds;
        } else {
            console.log("⚠️ data/odds.json exists but returned an error.");
            return null;
        }
    } catch (e) {
        console.log("No local odds.json file found. Ensure the Python cron job is running.");
        return null; 
    }
}
async function init(dateToFetch) {
    console.log(`🚀 Starting App. Fetching games for: ${dateToFetch}`);
    
    const container = document.getElementById('games-container');
    const datePicker = document.getElementById('date-picker');
    
    // Reset State
    ALL_GAMES_DATA = [];
    if (datePicker) datePicker.value = dateToFetch;

    if (container) {
        container.innerHTML = `
            <div class="col-12 text-center mt-5 pt-5">
                <div class="spinner-border text-primary" role="status"></div>
                <p class="mt-3 text-muted" id="loading-text">Loading Schedule...</p>
            </div>`;
    }
    
   const MLB_API_URL = `https://statsapi.mlb.com/api/v1/schedule?sportId=1&date=${dateToFetch}&hydrate=linescore,venue,probablePitcher,lineups,person`;
    
    try {
        let stadiumResponse = await fetch('data/stadiums.json');
        if (!stadiumResponse.ok) stadiumResponse = await fetch('stadiums.json');
        const stadiums = await stadiumResponse.json();

        const scheduleResponse = await fetch(MLB_API_URL);
        const scheduleData = await scheduleResponse.json();

        if (scheduleData.totalGames === 0) {
            container.innerHTML = `
                <div class="col-12 text-center mt-5">
                    <div class="alert alert-light shadow-sm py-4">
                        <h4 class="text-muted">No games scheduled for ${dateToFetch}</h4>
                        <p class="small text-muted mb-0">Spring Training starts Feb 20!</p>
                    </div>
                </div>`;
            return;
        }

        const rawGames = scheduleData.dates[0].games;
        const totalGames = rawGames.length;

        // --- FETCH ODDS FROM LOCAL SERVER ONLY ---
        let dailyOddsData = await fetchLocalOdds();
        
        // Loop through games
        for (let i = 0; i < totalGames; i++) {
            const game = rawGames[i];
            document.getElementById('loading-text').innerText = `Analyzing game ${i+1} of ${totalGames}...`;

            const venueId = game.venue.id;
            const stadium = stadiums.find(s => s.id === venueId);
            
            let weatherData = null;
            let windData = null;
            let isRoofClosed = false;

            if (stadium) {
                weatherData = await fetchGameWeather(stadium.lat, stadium.lon, game.gameDate);
                
                if (weatherData.status !== "too_early" && weatherData.temp !== '--') {
                    windData = calculateWind(weatherData.windDir, stadium.bearing);
                    
                    if (stadium.dome) isRoofClosed = true;
                    else if (stadium.roof) {
                        if (weatherData.maxPrecipChance > 30 || weatherData.temp < 50 || weatherData.temp > 95) isRoofClosed = true;
                    }
                    if (isRoofClosed) {
                        windData = { text: "Roof Closed", cssClass: "bg-secondary text-white", arrow: "" };
                        weatherData.windSpeed = 0; 
                    }
                }
            }

            // --- MATCH THE ODDS DATA TO THIS SPECIFIC GAME ---
            let gameOdds = null;
            if (dailyOddsData) {
                gameOdds = dailyOddsData.find(o => 
                    o.home_team === game.teams.home.team.name && 
                    o.away_team === game.teams.away.team.name
                );
            }
            // --- NEW: FETCH LINEUP HANDEDNESS DIRECTLY ---
            let lineupHandedness = {};
            const awayLineup = game.lineups?.awayPlayers || [];
            const homeLineup = game.lineups?.homePlayers || [];
            const lineupIds = [...awayLineup, ...homeLineup].map(p => p.id);

            // If lineups exist, fetch all 18 players in one batch request
            if (lineupIds.length > 0) {
                try {
                    const peopleRes = await fetch(`https://statsapi.mlb.com/api/v1/people?personIds=${lineupIds.join(',')}`);
                    const peopleData = await peopleRes.json();
                    if (peopleData.people) {
                        peopleData.people.forEach(person => {
                            lineupHandedness[person.id] = person.batSide?.code || "";
                        });
                    }
                } catch (e) { console.log("Failed to fetch lineup handedness"); }
            }

            ALL_GAMES_DATA.push({
                gameRaw: game,
                stadium: stadium,
                weather: weatherData,
                wind: windData,
                roof: isRoofClosed,
                odds: gameOdds,
                lineupHandedness: lineupHandedness
            });
        }

        renderGames();

    } catch (error) {
        console.error("❌ ERROR:", error);
        container.innerHTML = `<div class="col-12 text-center mt-5"><div class="alert alert-danger">${error.message}</div></div>`;
    }
}

// ==========================================
// 2. RENDERING ENGINE
// ==========================================

function renderGames() {
    const container = document.getElementById('games-container');
    container.innerHTML = '';

    const searchText = document.getElementById('team-search').value.toLowerCase();
    const sortMode = document.getElementById('sort-filter').value;
    const risksOnly = document.getElementById('risk-only').checked;

    let filteredGames = ALL_GAMES_DATA.filter(item => {
        const g = item.gameRaw;
        const teams = (g.teams.away.team.name + " " + g.teams.home.team.name).toLowerCase();
        
        // 1. Search Filter
        if (!teams.includes(searchText)) return false;

        // 2. Risk Filter (UPDATED: RAIN ONLY)
        if (risksOnly) {
            // If no weather data, hide it
            if (!item.weather || item.weather.temp === '--') return false; 
            
            // If roof is closed, it's never a risk
            if (item.roof) return false;

            // STRICT RULE: Only show if Rain >= 30%
            if (item.weather.maxPrecipChance < 30) return false;
        }
        return true;
    });

    // 3. Sorting
    filteredGames.sort((a, b) => {
        const aValid = a.weather && a.weather.temp !== '--';
        const bValid = b.weather && b.weather.temp !== '--';
        if (!aValid && bValid) return 1;
        if (aValid && !bValid) return -1;

        if (sortMode === 'wind') return (b.weather?.windSpeed || 0) - (a.weather?.windSpeed || 0);
        if (sortMode === 'rain') return (b.weather?.maxPrecipChance || 0) - (a.weather?.maxPrecipChance || 0);
        if (sortMode === 'temp') return (b.weather?.temp || 0) - (a.weather?.temp || 0);
        if (sortMode === 'humidity') return (b.weather?.humidity || 0) - (a.weather?.humidity || 0);
        
        return new Date(a.gameRaw.gameDate) - new Date(b.gameRaw.gameDate);
    });

    if (filteredGames.length === 0) {
        container.innerHTML = `<div class="col-12 text-center py-5 text-muted">No games match your filters.</div>`;
        return;
    }

    filteredGames.forEach(item => {
        container.appendChild(createGameCard(item));
    });
}

function createGameCard(data) {
    const game = data.gameRaw;
    const stadium = data.stadium;
    const weather = data.weather;
    const windInfo = data.wind;
    const isRoofClosed = data.roof;

    // --- 1. Risk Border Logic ---
    let borderClass = ""; 
    if (weather && !isRoofClosed) {
        let sustainedRainHours = 0;
        if (weather.hourly && weather.hourly.length > 0) {
            sustainedRainHours = weather.hourly.filter(h => h.precipChance >= 60).length;
        }

        if (weather.isThunderstorm) {
            borderClass = "border-danger border-3"; 
        } else if (sustainedRainHours >= 3) {
            borderClass = "border-danger border-3"; 
        } else if (weather.maxPrecipChance >= 30) {
            borderClass = "border-warning border-3"; 
        } 
    }

    // --- 2. Animated Background Logic ---
    let bgClass = "bg-weather-sunny"; 
    if (isRoofClosed) {
        bgClass = "bg-weather-roof";
    } else if (weather) {
        if (weather.isThunderstorm) bgClass = "bg-weather-storm";
        else if (weather.isSnow) bgClass = "bg-weather-snow";
        else if (weather.maxPrecipChance >= 50) bgClass = "bg-weather-rain";
        else if (weather.maxPrecipChance >= 20) bgClass = "bg-weather-cloudy";
        else if (weather.temp >= 90) bgClass = "bg-weather-sunny"; 
    }

    const gameCard = document.createElement('div');
    gameCard.className = 'col-md-6 col-lg-6 col-xl-4 animate-card mb-2';

    // Teams
    const awayAbbr = getTeamAbbr(game.teams.away.team.name);
    const homeAbbr = getTeamAbbr(game.teams.home.team.name);
    const awayId = game.teams.away.team.id;
    const homeId = game.teams.home.team.id;
    const awayName = game.teams.away.team.name;
    const homeName = game.teams.home.team.name;
    const awayLogo = `https://www.mlbstatic.com/team-logos/team-cap-on-light/${awayId}.svg`;
    const homeLogo = `https://www.mlbstatic.com/team-logos/team-cap-on-light/${homeId}.svg`;
    const gameTime = new Date(game.gameDate).toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'});

    // --- PITCHER LOGIC ---
    let awayPitcher = "TBD";
    if (game.teams.away.probablePitcher) {
        const pInfo = game.teams.away.probablePitcher;
        const hand = pInfo.pitchHand?.code ? ` (${pInfo.pitchHand.code})` : "";
        awayPitcher = pInfo.fullName + hand;
    }

    let homePitcher = "TBD";
    if (game.teams.home.probablePitcher) {
        const pInfo = game.teams.home.probablePitcher;
        const hand = pInfo.pitchHand?.code ? ` (${pInfo.pitchHand.code})` : "";
        homePitcher = pInfo.fullName + hand;
    }

    // --- 3. LINEUPS LOGIC ---
    const lineupAway = game.lineups?.awayPlayers || [];
    const lineupHome = game.lineups?.homePlayers || [];
    const handDict = data.lineupHandedness || {}; 

    const isLineupsExpanded = document.getElementById('show-lineups')?.checked;
    const collapseClass = isLineupsExpanded ? "collapse show" : "collapse";
    const ariaExpanded = isLineupsExpanded ? "true" : "false";

    const windText = windInfo?.text || "";
    const windSpeed = weather?.windSpeed || 0;
    const isWindImpactful = windSpeed >= 9; 

    const isWindOutToRight = isWindImpactful && windText.includes("Out to Right");
    const isWindOutToLeft = isWindImpactful && windText.includes("Out to Left");
    const isWindInFromRight = isWindImpactful && windText.includes("In from Right");
    const isWindInFromLeft = isWindImpactful && windText.includes("In from Left");

    const homePitcherHand = game.teams.home.probablePitcher?.pitchHand?.code || "";
    const awayPitcherHand = game.teams.away.probablePitcher?.pitchHand?.code || "";

    let awayLineupHtml = '';
    if (lineupAway.length > 0) {
        const list = lineupAway.map((p) => {
            const batCode = handDict[p.id]; 
            let itemStyle = "";
            let tooltip = "";
            
            if (batCode) {
                let effectiveBatSide = batCode;
                let switchNote = "";
                if (batCode === 'S' && homePitcherHand) {
                    effectiveBatSide = (homePitcherHand === 'R') ? 'L' : 'R';
                    switchNote = `Batting ${effectiveBatSide} vs ${homePitcherHand}HP - `;
                }

                if (isWindOutToRight && effectiveBatSide === 'L') {
                    itemStyle = "color: #198754;"; 
                    tooltip = `title='Favorable Matchup: ${switchNote}Wind blowing out to Right Field (${windSpeed}mph)'`;
                } else if (isWindOutToLeft && effectiveBatSide === 'R') {
                    itemStyle = "color: #198754;";
                    tooltip = `title='Favorable Matchup: ${switchNote}Wind blowing out to Left Field (${windSpeed}mph)'`;
                } else if (isWindInFromRight && effectiveBatSide === 'L') {
                    itemStyle = "color: #dc3545;"; 
                    tooltip = `title='Unfavorable Matchup: ${switchNote}Wind blowing in from Right Field (${windSpeed}mph)'`;
                } else if (isWindInFromLeft && effectiveBatSide === 'R') {
                    itemStyle = "color: #dc3545;";
                    tooltip = `title='Unfavorable Matchup: ${switchNote}Wind blowing in from Left Field (${windSpeed}mph)'`;
                }
            }

            const handHtml = batCode ? `<span style="font-weight:normal; opacity:0.8; color: inherit;"> (${batCode})</span>` : "";
            return `<li ${tooltip} style="${itemStyle} cursor: default;">${p.fullName}${handHtml}</li>`;
        }).join('');
        
        const collapseId = `lineup-away-${game.gamePk}`;
        awayLineupHtml = `
            <div class="mt-1">
                <a href="#${collapseId}" data-bs-toggle="collapse" aria-expanded="${ariaExpanded}" class="badge bg-primary text-white text-decoration-none" style="font-size: 0.65rem;">📋 View Lineup</a>
                <div class="${collapseClass} mt-1 text-start bg-light rounded p-2 border" id="${collapseId}">
                    <ol class="mb-0 ps-3 text-muted" style="font-size: 0.65rem; line-height: 1.3;">${list}</ol>
                </div>
            </div>`;
    }

    let homeLineupHtml = '';
    if (lineupHome.length > 0) {
        const list = lineupHome.map((p) => {
            const batCode = handDict[p.id]; 
            let itemStyle = "";
            let tooltip = "";
            
            if (batCode) {
                let effectiveBatSide = batCode;
                let switchNote = "";
                if (batCode === 'S' && awayPitcherHand) {
                    effectiveBatSide = (awayPitcherHand === 'R') ? 'L' : 'R';
                    switchNote = `Batting ${effectiveBatSide} vs ${awayPitcherHand}HP - `;
                }

                if (isWindOutToRight && effectiveBatSide === 'L') {
                    itemStyle = "color: #198754;"; 
                    tooltip = `title='Favorable Matchup: ${switchNote}Wind blowing out to Right Field (${windSpeed}mph)'`;
                } else if (isWindOutToLeft && effectiveBatSide === 'R') {
                    itemStyle = "color: #198754;";
                    tooltip = `title='Favorable Matchup: ${switchNote}Wind blowing out to Left Field (${windSpeed}mph)'`;
                } else if (isWindInFromRight && effectiveBatSide === 'L') {
                    itemStyle = "color: #dc3545;"; 
                    tooltip = `title='Unfavorable Matchup: ${switchNote}Wind blowing in from Right Field (${windSpeed}mph)'`;
                } else if (isWindInFromLeft && effectiveBatSide === 'R') {
                    itemStyle = "color: #dc3545;";
                    tooltip = `title='Unfavorable Matchup: ${switchNote}Wind blowing in from Left Field (${windSpeed}mph)'`;
                }
            }

            const handHtml = batCode ? `<span style="font-weight:normal; opacity:0.8; color: inherit;"> (${batCode})</span>` : "";
            return `<li ${tooltip} style="${itemStyle} cursor: default;">${p.fullName}${handHtml}</li>`;
        }).join('');
        
        const collapseId = `lineup-home-${game.gamePk}`;
        homeLineupHtml = `
            <div class="mt-1">
                <a href="#${collapseId}" data-bs-toggle="collapse" aria-expanded="${ariaExpanded}" class="badge bg-primary text-white text-decoration-none" style="font-size: 0.65rem;">📋 View Lineup</a>
                <div class="${collapseClass} mt-1 text-start bg-light rounded p-2 border" id="${collapseId}">
                    <ol class="mb-0 ps-3 text-muted" style="font-size: 0.65rem; line-height: 1.3;">${list}</ol>
                </div>
            </div>`;
    }

    // --- 4. BETTING ODDS UI (IN HEADER) ---
    const oddsData = data.odds; 
    let mlAway = ""; 
    let mlHome = "";
    let totalHtml = `<div class="text-muted small fw-bold pt-3">@</div>`;

    if (oddsData && oddsData.bookmakers && oddsData.bookmakers.length > 0) {
        const bookie = oddsData.bookmakers.find(b => b.key === 'fanduel') || oddsData.bookmakers[0];
        
        const h2hMarket = bookie.markets.find(m => m.key === 'h2h');
        if (h2hMarket) {
            const awayOutcome = h2hMarket.outcomes.find(o => o.name === awayName);
            const homeOutcome = h2hMarket.outcomes.find(o => o.name === homeName);
            
            if (awayOutcome) {
                const price = awayOutcome.price > 0 ? `+${awayOutcome.price}` : awayOutcome.price;
                mlAway = `<span class="badge bg-light text-dark border ms-1" style="font-size: 0.65rem; vertical-align: middle;">${price}</span>`;
            }
            if (homeOutcome) {
                const price = homeOutcome.price > 0 ? `+${homeOutcome.price}` : homeOutcome.price;
                mlHome = `<span class="badge bg-light text-dark border ms-1" style="font-size: 0.65rem; vertical-align: middle;">${price}</span>`;
            }
        }

        const totalsMarket = bookie.markets.find(m => m.key === 'totals');
        if (totalsMarket && totalsMarket.outcomes.length > 0) {
            const gameTotal = totalsMarket.outcomes[0].point; 
            totalHtml = `
                <div class="d-flex flex-column justify-content-center align-items-center pt-2">
                    <div class="text-muted small fw-bold mb-1">@</div>
                    <div class="badge bg-dark text-white shadow-sm" style="font-size: 0.65rem; letter-spacing: 0.5px;">O/U ${gameTotal}</div>
                </div>`;
        }
    }

    // --- 5. WEATHER & HOURLY DISPLAY ---
    let weatherHtml = `<div class="text-muted p-3 text-center small">Weather data unavailable.<br><span class="badge bg-light text-dark">Venue ID: ${game.venue.id}</span></div>`;

    if (stadium && weather) {
        if (weather.status === "too_early") {
            weatherHtml = `
                <div class="text-center p-3">
                    <h6 class="text-muted mb-1">🔭 Too Early to Forecast</h6>
                    <p class="small text-muted mb-0" style="font-size: 0.75rem;">Forecasts available ~14 days out.</p>
                </div>`;
        } else if (weather.temp !== '--') {
            const analysisText = generateMatchupAnalysis(weather, windInfo, isRoofClosed);
            
            let displayRain = isRoofClosed ? "0%" : `${weather.maxPrecipChance}%`;
            let precipLabel = "Rain"; 

            if (!isRoofClosed) {
                if (weather.isThunderstorm) displayRain += " ⚡";
                else if (weather.isSnow) { displayRain += " ❄️"; precipLabel = "Snow"; }
            }
            
            const radarUrl = `https://embed.windy.com/embed2.html?lat=${stadium.lat}&lon=${stadium.lon}&detailLat=${stadium.lat}&detailLon=${stadium.lon}&width=650&height=450&zoom=11&level=surface&overlay=rain&product=ecmwf&menu=&message=&marker=&calendar=now&pressure=&type=map&location=coordinates&detail=&metricWind=mph&metricTemp=%C2%B0F&radarRange=-1`;

            let hourlyHtml = '';
            if (isRoofClosed) {
                hourlyHtml = `<div class="text-center mt-2"><small class="text-muted">Indoor Conditions</small></div>`;
            } else if (weather.hourly && weather.hourly.length > 0) {
                const cardsHtml = weather.hourly.map((h, index) => {
                    const ampm = h.hour >= 12 ? 'PM' : 'AM';
                    const hour12 = h.hour % 12 || 12;
                    const timeLabel = `${hour12}${ampm}`;

                    let icon = '';
                    let popHtml = '&nbsp;'; 
                    const isNight = h.hour >= 20 || h.hour < 6;

                    if (h.precipChance >= 30) {
                        if (h.isThunderstorm) icon = '⛈️';
                        else if (h.isSnow) icon = '🌨️';
                        else icon = '🌧️';
                        popHtml = `${h.precipChance}%`;
                    } else if (h.precipChance > 0) {
                        icon = '⛅'; 
                        popHtml = `${h.precipChance}%`;
                    } else {
                        icon = isNight ? '🌙' : '☀️';
                    }
                    const tempDisplay = h.temp !== undefined ? `${h.temp}°` : '--';

                    return `
                        <div class="hour-card">
                            <div class="hour-time">${timeLabel}</div>
                            <div class="hour-icon">${icon}</div>
                            <div class="hour-pop">${popHtml}</div>
                            <div class="hour-temp">${tempDisplay}</div>
                        </div>`;
                }).join('');
                hourlyHtml = `<div class="hourly-scroll-container">${cardsHtml}</div>`;
            }
            
            const gameDataSafe = encodeURIComponent(JSON.stringify(data));

            // REMOVED old odds injection from here!
            weatherHtml = `
                <div class="weather-row row text-center align-items-center">
                    <div class="col-3 border-end px-1">
                        <div class="fw-bold">${weather.temp}°F</div>
                        <div class="small text-muted" style="font-size: 0.7rem;">Temp</div>
                    </div>
                    <div class="col-3 border-end px-1">
                        <div class="fw-bold text-dark">${weather.humidity}%</div>
                        <div class="small text-muted" style="font-size: 0.7rem;">Hum</div>
                    </div>
                    <div class="col-3 border-end px-1">
                        <div class="fw-bold text-primary" style="white-space: nowrap;">${displayRain}</div>
                        <div class="small text-muted" style="font-size: 0.7rem;">${precipLabel}</div>
                    </div>
                    <div class="col-3 px-1">
                        <div class="fw-bold">${weather.windSpeed} <span style="font-size:0.7em">mph</span></div>
                        <span class="wind-badge ${windInfo.cssClass}" style="font-size: 0.55rem; white-space: nowrap; display: inline-block; padding: 2px 4px;">
                            ${windInfo.arrow}
                        </span>
                    </div>
                </div>
                ${hourlyHtml}
                
                <div class="row g-2 mt-2">
                    <div class="col-8">
                        <button class="btn btn-sm btn-outline-primary w-100 py-1" onclick="showRadar('${radarUrl}', '${game.venue.name}')">
                            🗺️ View Radar
                        </button>
                    </div>
                    <div class="col-4">
                        <button class="btn btn-sm btn-dark w-100 py-1 d-flex align-items-center justify-content-center" onclick="shareGameTweet('${gameDataSafe}')">
                            <svg viewBox="0 0 24 24" width="12" height="12" fill="white" class="me-1"><path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z"></path></svg>
                            Tweet
                        </button>
                    </div>
                </div>

                <div class="analysis-box">
                    <span class="analysis-title">✨ Weather Impact</span>
                    ${analysisText}
                </div>`;
        }
    }

    // --- MAIN CARD HTML GENERATION ---
    gameCard.innerHTML = `
        <div class="card game-card h-100 ${borderClass} ${bgClass}">
            <div class="card-body p-3 pb-2"> 
                <div class="d-flex justify-content-between align-items-center mb-2">
                    <span class="badge bg-light text-dark border">${gameTime}</span>
                    <span class="stadium-name text-truncate" style="max-width: 180px;">${game.venue.name}</span>
                </div>
                
                <div class="d-flex justify-content-between align-items-start px-1">
                    <div class="text-center" style="width: 42%;"> 
                        <img src="${awayLogo}" alt="${awayName}" class="team-logo mb-1" onerror="this.style.display='none'">
                        <div class="fw-bold lh-1 d-flex justify-content-center align-items-center flex-wrap" style="font-size: 0.85rem; letter-spacing: -0.2px;">
                            ${awayName} ${mlAway}
                        </div>
                        <div class="text-muted mt-1" style="font-size: 0.7rem;">${awayPitcher}</div>
                        ${awayLineupHtml}
                    </div>
                    
                    <div class="text-center" style="width: 16%;">
                        ${totalHtml}
                    </div>
                    
                    <div class="text-center" style="width: 42%;"> 
                        <img src="${homeLogo}" alt="${homeName}" class="team-logo mb-1" onerror="this.style.display='none'">
                        <div class="fw-bold lh-1 d-flex justify-content-center align-items-center flex-wrap" style="font-size: 0.85rem; letter-spacing: -0.2px;">
                            ${homeName} ${mlHome}
                        </div>
                        <div class="text-muted mt-1" style="font-size: 0.7rem;">${homePitcher}</div>
                        ${homeLineupHtml}
                    </div>
                </div>
                
                ${weatherHtml}
            </div>
        </div>`;
    
    return gameCard;
}

// ==========================================
// 3. LISTENERS
// ==========================================

document.addEventListener('DOMContentLoaded', () => {
    // 1. Start App
    init(DEFAULT_DATE);

    // 2. Filter Listeners
    const searchInput = document.getElementById('team-search');
    const sortSelect = document.getElementById('sort-filter');
    const riskToggle = document.getElementById('risk-only');
    const lineupsToggle = document.getElementById('show-lineups');
    
    if(searchInput) searchInput.addEventListener('input', renderGames);
    if(sortSelect) sortSelect.addEventListener('change', renderGames);
    if(riskToggle) riskToggle.addEventListener('change', renderGames);
    if(lineupsToggle) lineupsToggle.addEventListener('change', renderGames);

    // 3. Date Picker Listener (UPDATED)
    const datePicker = document.getElementById('date-picker');
    
    if (datePicker) {
        // Set initial value
        datePicker.value = DEFAULT_DATE;

        // Listen for changes
        datePicker.addEventListener('change', (e) => {
            if (e.target.value) {
                // Close keyboard on mobile
                e.target.blur(); 
                
                // --- NEW: Reset Filters on Date Change ---
                const riskToggle = document.getElementById('risk-only');
                if (riskToggle) riskToggle.checked = false;

               // const lineupsToggle = document.getElementById('show-lineups');
              //  if (lineupsToggle) lineupsToggle.checked = false;
                
                // Fetch new games
                init(e.target.value);
            }
        });
    }
    // Stop radar iframe from burning data in the background when closed
    const radarModal = document.getElementById('radarModal');
    if (radarModal) {
        radarModal.addEventListener('hidden.bs.modal', () => {
            const iframe = document.getElementById('radarFrame');
            if (iframe) iframe.src = ''; 
        });
    }
});

// ==========================================
// 4. HELPER FUNCTIONS
// ==========================================
function getWindArrowEmoji(direction) {
    // 1. Handle missing data
    if (direction === null || direction === undefined) return "💨";

    // 2. Handle Degrees (if the API sends a number like 180, 270)
    if (typeof direction === 'number') {
        const val = Math.floor((direction / 22.5) + 0.5);
        const arr = ["N", "NNE", "NE", "ENE", "E", "ESE", "SE", "SSE", "S", "SSW", "SW", "WSW", "W", "WNW", "NW", "NNW"];
        direction = arr[(val % 16)];
    }

    // 3. Map Compass String to Arrow Emoji
    const map = {
        "N": "⬇️",   "NNE": "⬇️", "NE": "↙️",  "ENE": "↙️", // Wind from North flows Down/South
        "E": "⬅️",   "ESE": "⬅️", "SE": "↖️",  "SSE": "↖️", // Wind from East flows Left/West
        "S": "⬆️",   "SSW": "⬆️", "SW": "↗️",  "WSW": "↗️", // Wind from South flows Up/North
        "W": "➡️",   "WNW": "➡️", "NW": "↘️",  "NNW": "↘️"  // Wind from West flows Right/East
    };

    // Note: Weather arrows usually point "Where the wind is going", 
    // so a North wind (From North) points Down (South).
    
    return map[direction.toUpperCase()] || "💨";
}

// Helper: Get Standard 3-Letter Code
function getTeamAbbr(teamName) {
    const map = {
        // Shared Cities (Must be 3 letters)
        "Yankees": "NYY", "Mets": "NYM",
        "Cubs": "CHC", "White Sox": "CWS",
        "Dodgers": "LAD", "Angels": "LAA",
        
        // The Rest (Standard Scoreboard Codes)
        "Diamondbacks": "ARI", "Braves": "ATL", "Orioles": "BAL", "Red Sox": "BOS",
        "Reds": "CIN", "Guardians": "CLE", "Rockies": "COL", "Tigers": "DET",
        "Astros": "HOU", "Royals": "KC",  "Marlins": "MIA", "Brewers": "MIL",
        "Twins": "MIN", "Athletics": "OAK", "Phillies": "PHI", "Pirates": "PIT",
        "Padres": "SD",  "Giants": "SF",  "Mariners": "SEA", "Cardinals": "STL",
        "Rays": "TB",   "Rangers": "TEX", "Blue Jays": "TOR", "Nationals": "WSH"
    };

    // Find key match
    const key = Object.keys(map).find(k => teamName.includes(k));
    return key ? map[key] : "MLB"; // Default
}


window.showRadar = function(url, venueName) {
    const modalElement = document.getElementById('radarModal');
    const modalTitle = document.querySelector('#radarModal .modal-title');
    const iframe = document.getElementById('radarFrame');
    
    if(modalTitle) modalTitle.innerText = `Radar: ${venueName}`;

    // 1. Get the modal safely without creating duplicates
    const myModal = bootstrap.Modal.getOrCreateInstance(modalElement);

    // 2. Clear out any old map data so it doesn't flash the previous city
    if(iframe) iframe.src = '';

    // 3. Define the load action
    const loadMap = function () {
        if(iframe) iframe.src = url; // Inject URL ONLY when fully visible
        modalElement.removeEventListener('shown.bs.modal', loadMap); // Clean up
    };

    // 4. Listen for the modal to finish opening, then load the map
    modalElement.addEventListener('shown.bs.modal', loadMap);
    
    // 5. Trigger the modal to open
    myModal.show();
}

function generateMatchupAnalysis(weather, windInfo, isRoofClosed) {
    if (isRoofClosed) return "Roof closed. Controlled environment with zero weather impact.";

    let notes = [];

    // 1. Safety Hazards (Lightning & Snow)
    if (weather.isThunderstorm) {
        notes.push("⚡ <b>Lightning Risk:</b> Thunderstorms detected. Mandatory 30-minute safety delays are likely.");
    }
    if (weather.isSnow) {
        notes.push("❄️ <b>Snow Risk:</b> Low visibility and slippery field conditions could delay play.");
    }

    // 2. Rain Analysis
    let sustainedRainHours = 0;
    if (weather.hourly && weather.hourly.length > 0) {
        // Count how many hours in our game window have a 60%+ chance of rain
        sustainedRainHours = weather.hourly.filter(h => h.precipChance >= 60).length;
    }

    if (sustainedRainHours >= 3) {
        notes.push("🌧️ <b>Rainout Risk:</b> Sustained heavy rain. High probability of postponement.");
    } else if (weather.maxPrecipChance >= 70) {
        notes.push("☔ <b>Severe Delay Risk:</b> Heavy rain expected, but should pass. Delays likely.");
    } else if (weather.maxPrecipChance >= 30) {
        notes.push("☔ <b>Delay Risk:</b> Scattered showers could interrupt play.");
    }

    // 3. Humidity Analysis
    if (weather.humidity <= 30) {
        notes.push("🌵 <b>Dry Air (<30%):</b> Sharp breaking balls (Pitcher Adv), but the ball travels up to 4.5ft farther (Hitter Adv).");
    } else if (weather.humidity >= 70) {
        notes.push("💧 <b>High Humidity (>70%):</b> Breaking balls hang/flatten (Hitter Adv), but the ball travels shorter distances (Pitcher Adv).");
    }

    // 4. Temp Analysis
    if (weather.temp >= 85) {
        notes.push("🔥 <b>Hitter Friendly:</b> High temps reduce air density, helping fly balls carry.");
    } else if (weather.temp <= 50) {
        notes.push("❄️ <b>Pitcher Friendly:</b> Cold, dense air suppresses ball flight and scoring.");
    }

    // 5. Wind Analysis
    if (weather.windSpeed >= 8) {
        const dir = windInfo.text;
        if (dir.includes("Blowing OUT")) notes.push("🚀 <b>Home Runs:</b> Strong wind blowing out creates ideal hitting conditions.");
        else if (dir.includes("Blowing IN")) notes.push("🛑 <b>Suppressed:</b> Wind blowing in will knock down fly balls. Advantage pitchers.");
        else if (dir.includes("Out to Right")) notes.push("↗️ <b>Lefty Advantage:</b> Wind blowing out to Right Field favors <b>Left-Handed</b> power.");
        else if (dir.includes("Out to Left")) notes.push("↖️ <b>Righty Advantage:</b> Wind blowing out to Left Field favors <b>Right-Handed</b> power.");
        else if (dir.includes("In from Right")) notes.push("📉 <b>Lefty Nightmare:</b> Wind blowing in from Right knocks down Lefty power.");
        else if (dir.includes("In from Left")) notes.push("📉 <b>Righty Nightmare:</b> Wind blowing in from Left knocks down Righty power.");
        else if (dir.includes("Cross")) notes.push("↔️ <b>Tricky:</b> Crosswinds may affect outfield defense and breaking balls.");
    }

    if (notes.length === 0) return "✅ <b>Neutral:</b> Fair weather conditions. No significant advantage.";
    return notes.join("<br>");
}

async function fetchGameWeather(lat, lon, gameDateIso) {
    const dateStr = gameDateIso.split('T')[0];
    const today = new Date().toLocaleDateString('en-CA'); 
    const isHistorical = dateStr < today; 
    const daysDiff = (new Date(dateStr) - new Date(today)) / (1000 * 60 * 60 * 24);

    if (!isHistorical && daysDiff > 16) return { status: "too_early", temp: '--' };

    let url = "";
    
    // CHANGED: We now use timezone=GMT so our array index perfectly matches the UTC game time
    if (isHistorical || dateStr === "2024-09-25") {
         url = `https://archive-api.open-meteo.com/v1/archive?latitude=${lat}&longitude=${lon}&start_date=${dateStr}&end_date=${dateStr}&hourly=temperature_2m,relative_humidity_2m,precipitation,weather_code,wind_speed_10m,wind_direction_10m&temperature_unit=fahrenheit&wind_speed_unit=mph&precipitation_unit=inch&timezone=GMT`;
    } 
    else if (daysDiff <= 3) {
         url = `https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&hourly=temperature_2m,relative_humidity_2m,precipitation_probability,precipitation,weather_code,wind_speed_10m,wind_direction_10m&temperature_unit=fahrenheit&wind_speed_unit=mph&precipitation_unit=inch&timezone=GMT&start_date=${dateStr}&end_date=${dateStr}`;
    }
    else {
         url = `https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&hourly=temperature_2m,relative_humidity_2m,precipitation_probability,precipitation,weather_code,wind_speed_10m,wind_direction_10m&models=gfs_seamless&temperature_unit=fahrenheit&wind_speed_unit=mph&precipitation_unit=inch&timezone=GMT&start_date=${dateStr}&end_date=${dateStr}`;
    }

    try {
        const response = await fetch(url);
        if (!response.ok) {
            if (response.status === 400) return { status: "too_early", temp: '--' };
            return { temp: '--', hourly: [] };
        }
        const data = await response.json();
        
        // CHANGED: Grab the UTC hour to precisely map to the GMT API array
        const gameHour = new Date(gameDateIso).getUTCHours();
        
        // --- UPDATED: AGGRESSIVE RAIN NORMALIZATION ---
        const normalizePrecip = (index) => {
            let prob = data.hourly.precipitation_probability ? data.hourly.precipitation_probability[index] || 0 : 0;
            let amount = data.hourly.precipitation ? data.hourly.precipitation[index] || 0 : 0;
            let code = data.hourly.weather_code[index];
            
            // 1. Eliminate "Phantom" Probability Blocks
            // If the volume is 0.00 and the weather code is Clear/Partly Cloudy (0, 1, 2, 3), force it to 0%
            if (amount === 0 && code <= 3) {
                return 0; 
            }

            // 2. Base percentage on actual expected volume to create dynamic hour-by-hour changes
            if (amount > 0) {
                if (amount >= 0.10) return Math.max(80, prob); // Heavy Rain
                if (amount >= 0.05) return Math.max(60, prob); // Moderate Rain
                if (amount >= 0.01) return Math.max(30, prob); // Light Rain
                return 15; // Trace amounts / Drizzle
            }
            
            return prob;
        };

        const hourlySlice = [];
        let maxChanceInWindow = 0;
        let isGameThunderstorm = false;
        let isGameSnow = false; 

        for (let i = gameHour - 1; i <= gameHour + 3; i++) {
            if (i >= 0 && i < 24) {
                let chance = normalizePrecip(i);
                
                const code = data.hourly.weather_code[i];
                const isHourThunderstorm = (code >= 95 && code <= 99);
                const isHourSnow = (code === 71 || code === 73 || code === 75 || code === 77 || code === 85 || code === 86);

                if (isHourThunderstorm) isGameThunderstorm = true;
                if (isHourSnow) isGameSnow = true;

                if (i >= gameHour && i <= gameHour + 3 && chance > maxChanceInWindow) maxChanceInWindow = chance;
                
                // Convert UTC hour back to the user's Local hour just for display on the UI
                let localHour = new Date(gameDateIso);
                localHour.setUTCHours(i);
                
                hourlySlice.push({ 
                    hour: localHour.getHours(), // UI shows local time
                    temp: Math.round(data.hourly.temperature_2m[i]), 
                    precipChance: chance,
                    isThunderstorm: isHourThunderstorm,
                    isSnow: isHourSnow 
                });
            }
        }

        return {
            status: "ok",
            temp: Math.round(data.hourly.temperature_2m[gameHour]),
            humidity: Math.round(data.hourly.relative_humidity_2m[gameHour]),
            maxPrecipChance: maxChanceInWindow, 
            isThunderstorm: isGameThunderstorm,
            isSnow: isGameSnow, 
            windSpeed: Math.round(data.hourly.wind_speed_10m[gameHour]),
            windDir: data.hourly.wind_direction_10m[gameHour],
            hourly: hourlySlice
        };
    } catch (e) {
        console.error("⚠️ Weather fetch failed:", e);
        return { temp: '--', hourly: [] };
    }
}

function calculateWind(windDirection, stadiumBearing) {
    let diff = (windDirection - stadiumBearing + 360) % 360;
    if (diff >= 337.5 || diff < 22.5) return { text: "Blowing IN", cssClass: "bg-in", arrow: "⬇" };
    if (diff >= 22.5 && diff < 67.5) return { text: "In from Right", cssClass: "bg-in", arrow: "↙" };
    if (diff >= 67.5 && diff < 112.5) return { text: "Cross (R to L)", cssClass: "bg-cross", arrow: "⬅" };
    if (diff >= 112.5 && diff < 157.5) return { text: "Out to Left", cssClass: "bg-out", arrow: "↖" };
    if (diff >= 157.5 && diff < 202.5) return { text: "Blowing OUT", cssClass: "bg-out", arrow: "⬆" };
    if (diff >= 202.5 && diff < 247.5) return { text: "Out to Right", cssClass: "bg-out", arrow: "↗" };
    if (diff >= 247.5 && diff < 292.5) return { text: "Cross (L to R)", cssClass: "bg-cross", arrow: "➡" };
    return { text: "In from Left", cssClass: "bg-in", arrow: "↘" };
}

window.shareGameTweet = function(encodedData) {
    const data = JSON.parse(decodeURIComponent(encodedData));
    const g = data.gameRaw;
    const w = data.weather;
    const s = data.stadium;
    const wind = data.wind;

    const away = g.teams.away.team.name;
    const home = g.teams.home.team.name;
    const venue = g.venue.name;

    let tweet = "";

    // --- 1. DETECT MODE ---
    const isHazard = w.maxPrecipChance >= 30 || w.isThunderstorm || w.isSnow;
    const isHitterFriendly = w.temp >= 85 || (w.windSpeed >= 10 && wind.text.includes("OUT"));
    const isPitcherFriendly = w.temp <= 50 || (w.windSpeed >= 10 && wind.text.includes("IN"));

    // --- 2. BUILD HEADER ---
    if (isHazard) {
        tweet += `⚠️ WEATHER ALERT: ${away} @ ${home}\n`;
        tweet += `🏟️ ${venue}\n\n`;
        
        // Hazard Line
        if (w.isThunderstorm) tweet += `⚡ LIGHTNING RISK DETECTED\n`;
        else if (w.isSnow) tweet += `❄️ SNOW RISK DETECTED\n`;
        else tweet += `☔ RAIN DELAY RISK (${w.maxPrecipChance}%)\n`;
    } else {
        tweet += `⚾ ${away} @ ${home}\n`;
        tweet += `🏟️ ${venue}\n\n`;
    }

    // --- 3. CONDITIONS ---
    tweet += `🌡️ Temp: ${w.temp}°F\n`;
    tweet += `💧 Hum: ${w.humidity}%\n`;
    tweet += `💨 Wind: ${w.windSpeed}mph (${wind.text} ${wind.arrow})\n`;
    
    if (!isHazard) {
        tweet += `☔ Rain: ${w.maxPrecipChance}%\n`;
    }

    // --- 4. SMART ANALYSIS ---
    tweet += `\n`;
    if (isHitterFriendly) {
        tweet += `🔥 IMPACT: Hitter Friendly! Ball carrying farther.\n`;
    } else if (isPitcherFriendly) {
        tweet += `❄️ IMPACT: Pitcher Friendly! Air density suppressing runs.\n`;
    } else if (w.humidity <= 30) {
        tweet += `🌵 IMPACT: Dry Air! Breaking balls sharp, but fly balls carry.\n`;
    }

    // --- 5. FOOTER ---
    tweet += `\n🔗 https://weathermlb.com\n#MLB #FantasyBaseball`;

    // --- 6. LAUNCH ---
    const twitterUrl = `https://twitter.com/intent/tweet?text=${encodeURIComponent(tweet)}`;
    window.open(twitterUrl, '_blank');
}

function generateDailyReport() {
    if (ALL_GAMES_DATA.length === 0) {
        alert("No games data available to report!");
        return;
    }

    const sortedGames = [...ALL_GAMES_DATA].sort((a, b) => 
        new Date(a.gameRaw.gameDate) - new Date(b.gameRaw.gameDate)
    );

    const MAX_TWEET_LENGTH = 260; 
    const today = new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
    
    let allLines = [];
    sortedGames.forEach(game => {
        const teams = game.gameRaw.teams;
        const w = game.weather; 
        
        const away = getTeamAbbr(teams.away.team.name);
        const home = getTeamAbbr(teams.home.team.name);
        
        let arrow = "💨";
        if (game.wind && game.wind.arrow) {
             arrow = game.wind.arrow;
        } else {
             arrow = getWindArrowEmoji(game.windDirection);
        }

        const rain = Math.round(Number(w.maxPrecipChance) || 0);
        const temp = Math.round(Number(w.temp) || 0);
        const windSpd = Math.round(Number(w.windSpeed) || 0);

        const line = `${away}@${home}:🌧️${rain}%🌡️${temp}°${arrow}${windSpd}mph`;
        allLines.push(line);
    });

    let tweets = [];
    let currentTweet = `⚾MLB Weather•${today} (1/X)\n\n`; 

    allLines.forEach((line) => {
        if ((currentTweet.length + line.length + 1) > MAX_TWEET_LENGTH) {
            tweets.push(currentTweet); 
            currentTweet = `(2/X) Continued...\n\n`; 
        }
        currentTweet += line + "\n";
    });

    currentTweet += `\nMore details: https://weathermlb.com\n#MLB #BaseballWeather`;
    tweets.push(currentTweet);

    const finalOutput = tweets.map((t, i) => `--- TWEET ${i+1} ---\n${t}\n`).join("\n");

    const textArea = document.getElementById('tweet-text');
    const twitterLink = document.getElementById('twitter-link');
    
    if (textArea) {
        textArea.value = finalOutput;

        if (twitterLink && tweets.length > 0) {
            const firstTweetBody = tweets[0]; 
            const twitterUrl = `https://twitter.com/intent/tweet?text=${encodeURIComponent(firstTweetBody)}`;
            twitterLink.href = twitterUrl;
        }
        
        const modalElement = document.getElementById('tweetModal');
        if (modalElement && typeof bootstrap !== 'undefined') {
            const modal = new bootstrap.Modal(modalElement);
            modal.show();
        } else {
             alert("Report generated (Modal not found):\n\n" + finalOutput);
        }
    }
}
