// ==========================================
// CONFIGURATION
// ==========================================
const DEFAULT_DATE = new Date().toLocaleDateString('en-CA');

// Global State
let ALL_GAMES_DATA = []; 

// ==========================================
// 1. MAIN APP LOGIC
// ==========================================
// --- LOCAL ODDS MATCHER ---

async function fetchLocalOdds() {
    try {
        console.log("Checking local odds file generated by Python...");
        const response = await fetch('data/odds.json?v=' + new Date().getTime()); 
        
        if (response.ok) {
            const fileData = await response.json();
            console.log(`✅ Loaded ${fileData.game_count} odds from server (Last updated: ${new Date(fileData.last_updated).toLocaleTimeString()})`);
            return fileData.odds;
        } else {
            console.log("⚠️ data/odds.json exists but returned an error.");
            return null;
        }
    } catch (e) {
        console.log("No local odds.json file found. Ensure the Python cron job is running.");
        return null; 
    }
}
async function init(dateToFetch) {
    console.log(`🚀 Starting App. Fetching games for: ${dateToFetch}`);
    
    const container = document.getElementById('games-container');
    const datePicker = document.getElementById('date-picker');
    
    // Reset State
    ALL_GAMES_DATA = [];
    if (datePicker) datePicker.value = dateToFetch;

    if (container) {
        container.innerHTML = `
            <div class="col-12 text-center mt-5 pt-5">
                <div class="spinner-border text-primary" role="status"></div>
                <p class="mt-3 text-muted" id="loading-text">Loading Schedule...</p>
            </div>`;
    }
    
   const MLB_API_URL = `https://statsapi.mlb.com/api/v1/schedule?sportId=1&date=${dateToFetch}&hydrate=linescore,venue,probablePitcher,lineups,person`;
    
    try {
        let stadiumResponse = await fetch('data/stadiums.json');
        if (!stadiumResponse.ok) stadiumResponse = await fetch('stadiums.json');
        const stadiums = await stadiumResponse.json();

        const scheduleResponse = await fetch(MLB_API_URL);
        const scheduleData = await scheduleResponse.json();

        if (scheduleData.totalGames === 0) {
            container.innerHTML = `
                <div class="col-12 text-center mt-5">
                    <div class="alert alert-light shadow-sm py-4">
                        <h4 class="text-muted">No games scheduled for ${dateToFetch}</h4>
                        <p class="small text-muted mb-0">Spring Training starts Feb 20!</p>
                    </div>
                </div>`;
            return;
        }

        const rawGames = scheduleData.dates[0].games;
        const totalGames = rawGames.length;

        let dailyOddsData = await fetchLocalOdds();
        
        for (let i = 0; i < totalGames; i++) {
            const game = rawGames[i];
            document.getElementById('loading-text').innerText = `Analyzing game ${i+1} of ${totalGames}...`;

            const venueId = game.venue.id;
            const stadium = stadiums.find(s => s.id === venueId);
            
            let weatherData = null;
            let windData = null;
            let isRoofClosed = false;

            if (stadium) {
                weatherData = await fetchGameWeather(stadium.lat, stadium.lon, game.gameDate);
                
                if (weatherData.status !== "too_early" && weatherData.temp !== '--') {
                    windData = calculateWind(weatherData.windDir, stadium.bearing);
                    
                    if (stadium.dome) isRoofClosed = true;
                    else if (stadium.roof) {
                        if (weatherData.maxPrecipChance > 30 || weatherData.temp < 50 || weatherData.temp > 95) isRoofClosed = true;
                    }
                    if (isRoofClosed) {
                        windData = { text: "Roof Closed", cssClass: "bg-secondary text-white", arrow: "" };
                        weatherData.windSpeed = 0; 
                    }
                }
            }

            let gameOdds = null;
            if (dailyOddsData) {
                gameOdds = dailyOddsData.find(o => 
                    o.home_team === game.teams.home.team.name && 
                    o.away_team === game.teams.away.team.name
                );
            }
            
            let lineupHandedness = {};
            const awayLineup = game.lineups?.awayPlayers || [];
            const homeLineup = game.lineups?.homePlayers || [];
            const lineupIds = [...awayLineup, ...homeLineup].map(p => p.id);

            if (lineupIds.length > 0) {
                try {
                    const peopleRes = await fetch(`https://statsapi.mlb.com/api/v1/people?personIds=${lineupIds.join(',')}`);
                    const peopleData = await peopleRes.json();
                    if (peopleData.people) {
                        peopleData.people.forEach(person => {
                            lineupHandedness[person.id] = person.batSide?.code || "";
                        });
                    }
                } catch (e) { console.log("Failed to fetch lineup handedness"); }
            }

            ALL_GAMES_DATA.push({
                gameRaw: game,
                stadium: stadium,
                weather: weatherData,
                wind: windData,
                roof: isRoofClosed,
                odds: gameOdds,
                lineupHandedness: lineupHandedness
            });
        }

        renderGames();

    } catch (error) {
        console.error("❌ ERROR:", error);
        container.innerHTML = `<div class="col-12 text-center mt-5"><div class="alert alert-danger">${error.message}</div></div>`;
    }
}

// ==========================================
// 2. RENDERING ENGINE
// ==========================================

function renderGames() {
    const container = document.getElementById('games-container');
    container.innerHTML = '';

    const searchText = document.getElementById('team-search').value.toLowerCase();
    const sortMode = document.getElementById('sort-filter').value;
    const risksOnly = document.getElementById('risk-only').checked;

    let filteredGames = ALL_GAMES_DATA.filter(item => {
        const g = item.gameRaw;
        const teams = (g.teams.away.team.name + " " + g.teams.home.team.name).toLowerCase();
        
        if (!teams.includes(searchText)) return false;

        if (risksOnly) {
            if (!item.weather || item.weather.temp === '--') return false; 
            if (item.roof) return false;
            if (item.weather.maxPrecipChance < 30) return false;
        }
        return true;
    });

    filteredGames.sort((a, b) => {
        const aValid = a.weather && a.weather.temp !== '--';
        const bValid = b.weather && b.weather.temp !== '--';
        if (!aValid && bValid) return 1;
        if (aValid && !bValid) return -1;

        if (sortMode === 'wind') return (b.weather?.windSpeed || 0) - (a.weather?.windSpeed || 0);
        if (sortMode === 'rain') return (b.weather?.maxPrecipChance || 0) - (a.weather?.maxPrecipChance || 0);
        if (sortMode === 'temp') return (b.weather?.temp || 0) - (a.weather?.temp || 0);
        if (sortMode === 'humidity') return (b.weather?.humidity || 0) - (a.weather?.humidity || 0);
        
        return new Date(a.gameRaw.gameDate) - new Date(b.gameRaw.gameDate);
    });

    if (filteredGames.length === 0) {
        container.innerHTML = `<div class="col-12 text-center py-5 text-muted">No games match your filters.</div>`;
        return;
    }

    filteredGames.forEach(item => {
        container.appendChild(createGameCard(item));
    });
}

function createGameCard(data) {
    const game = data.gameRaw;
    const stadium = data.stadium;
    const weather = data.weather;
    const windInfo = data.wind;
    const isRoofClosed = data.roof;

    // --- 1. Risk Border Logic (UPDATED FOR DURATION) ---
    let borderClass = ""; 
    if (weather && !isRoofClosed) {
        let sustainedRainHours = 0;
        if (weather.hourly && weather.hourly.length > 0) {
            sustainedRainHours = weather.hourly.filter(h => h.precipChance >= 60).length;
        }

        if (weather.isThunderstorm) {
            borderClass = "border-danger border-3"; 
        } else if (sustainedRainHours >= 3) {
            borderClass = "border-danger border-3"; 
        } else if (weather.maxPrecipChance >= 30) {
            borderClass = "border-warning border-3"; 
        } 
    }

    // --- 2. Animated Background Logic ---
    let bgClass = "bg-weather-sunny"; 
    if (isRoofClosed) {
        bgClass = "bg-weather-roof";
    } else if (weather) {
        if (weather.isThunderstorm) bgClass = "bg-weather-storm";
        else if (weather.isSnow) bgClass = "bg-weather-snow";
        else if (weather.maxPrecipChance >= 50) bgClass = "bg-weather-rain";
        else if (weather.maxPrecipChance >= 20) bgClass = "bg-weather-cloudy";
        else if (weather.temp >= 90) bgClass = "bg-weather-sunny"; 
    }

    const gameCard = document.createElement('div');
    gameCard.className = 'col-md-6 col-lg-4 col-xl-3 col-xxl-2 animate-card mb-2';

    // Teams (Full names for logic, Short names for UI)
    const awayAbbr = getTeamAbbr(game.teams.away.team.name);
    const homeAbbr = getTeamAbbr(game.teams.home.team.name);
    const awayId = game.teams.away.team.id;
    const homeId = game.teams.home.team.id;
    
    const awayName = game.teams.away.team.name; // Full name for Odds match
    const homeName = game.teams.home.team.name; // Full name for Odds match
    
    // UI Short Names (e.g., "Diamondbacks", "Red Sox")
    const awayShortName = getShortTeamName(awayName); 
    const homeShortName = getShortTeamName(homeName);

    const awayLogo = `https://www.mlbstatic.com/team-logos/team-cap-on-light/${awayId}.svg`;
    const homeLogo = `https://www.mlbstatic.com/team-logos/team-cap-on-light/${homeId}.svg`;
    const gameTime = new Date(game.gameDate).toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'});

    // --- PITCHER LOGIC (UPDATED WITH F. LASTNAME FORMAT) ---
    let awayPitcher = "TBD";
    if (game.teams.away.probablePitcher) {
        const pInfo = game.teams.away.probablePitcher;
        const hand = pInfo.pitchHand?.code ? ` (${pInfo.pitchHand.code})` : "";
        awayPitcher = formatPlayerName(pInfo.fullName) + hand;
    }

    let homePitcher = "TBD";
    if (game.teams.home.probablePitcher) {
        const pInfo = game.teams.home.probablePitcher;
        const hand = pInfo.pitchHand?.code ? ` (${pInfo.pitchHand.code})` : "";
        homePitcher = formatPlayerName(pInfo.fullName) + hand;
    }

    // --- 3. LINEUPS LOGIC ---
    const lineupAway = game.lineups?.awayPlayers || [];
    const lineupHome = game.lineups?.homePlayers || [];
    const handDict = data.lineupHandedness || {}; 

    const isLineupsExpanded = document.getElementById('show-lineups')?.checked;
    const collapseClass = isLineupsExpanded ? "collapse show" : "collapse";
    const ariaExpanded = isLineupsExpanded ? "true" : "false";

    const windText = windInfo?.text || "";
    const windSpeed = weather?.windSpeed || 0;
    const isWindImpactful = windSpeed >= 9; 

    const isWindOutToRight = isWindImpactful && windText.includes("Out to Right");
    const isWindOutToLeft = isWindImpactful && windText.includes("Out to Left");
    const isWindInFromRight = isWindImpactful && windText.includes("In from Right");
    const isWindInFromLeft = isWindImpactful && windText.includes("In from Left");

    const homePitcherHand = game.teams.home.probablePitcher?.pitchHand?.code || "";
    const awayPitcherHand = game.teams.away.probablePitcher?.pitchHand?.code || "";

    let awayLineupHtml = '';
    if (lineupAway.length > 0) {
        const list = lineupAway.map((p) => {
            const batCode = handDict[p.id]; 
            let itemStyle = "";
            let tooltip = "";
            
            if (batCode) {
                let effectiveBatSide = batCode;
                let switchNote = "";
                if (batCode === 'S' && homePitcherHand) {
                    effectiveBatSide = (homePitcherHand === 'R') ? 'L' : 'R';
                    switchNote = `Batting ${effectiveBatSide} vs ${homePitcherHand}HP - `;
                }

                if (isWindOutToRight && effectiveBatSide === 'L') {
                    itemStyle = "color: #198754;"; 
                    tooltip = `title='Favorable Matchup: ${switchNote}Wind blowing out to Right Field (${windSpeed}mph)'`;
                } else if (isWindOutToLeft && effectiveBatSide === 'R') {
                    itemStyle = "color: #198754;";
                    tooltip = `title='Favorable Matchup: ${switchNote}Wind blowing out to Left Field (${windSpeed}mph)'`;
                } else if (isWindInFromRight && effectiveBatSide === 'L') {
                    itemStyle = "color: #dc3545;"; 
                    tooltip = `title='Unfavorable Matchup: ${switchNote}Wind blowing in from Right Field (${windSpeed}mph)'`;
                } else if (isWindInFromLeft && effectiveBatSide === 'R') {
                    itemStyle = "color: #dc3545;";
                    tooltip = `title='Unfavorable Matchup: ${switchNote}Wind blowing in from Left Field (${windSpeed}mph)'`;
                }
            }

            const handHtml = batCode ? `<span style="font-weight:normal; opacity:0.8; color: inherit;"> (${batCode})</span>` : "";
            return `<li ${tooltip} style="${itemStyle} cursor: default;">${formatPlayerName(p.fullName)}${handHtml}</li>`;
        }).join('');
        
        const collapseId = `lineup-away-${game.gamePk}`;
        awayLineupHtml = `
            <div class="mt-0 w-100"> 
                <a href="#${collapseId}" data-bs-toggle="collapse" aria-expanded="${ariaExpanded}" class="badge bg-primary text-white text-decoration-none" style="font-size: 0.65rem;">📋 View Lineup</a>
                <div class="${collapseClass} mt-1 text-start bg-light rounded p-1 border w-100" id="${collapseId}">
                    <ol class="mb-0 pe-0 text-muted w-100" style="padding-left: 1.1rem; font-size: 0.65rem; line-height: 1.3;">${list}</ol>
                </div>
            </div>`;
    }

    let homeLineupHtml = '';
    if (lineupHome.length > 0) {
        const list = lineupHome.map((p) => {
            const batCode = handDict[p.id]; 
            let itemStyle = "";
            let tooltip = "";
            
            if (batCode) {
                let effectiveBatSide = batCode;
                let switchNote = "";
                if (batCode === 'S' && awayPitcherHand) {
                    effectiveBatSide = (awayPitcherHand === 'R') ? 'L' : 'R';
                    switchNote = `Batting ${effectiveBatSide} vs ${awayPitcherHand}HP - `;
                }

                if (isWindOutToRight && effectiveBatSide === 'L') {
                    itemStyle = "color: #198754;"; 
                    tooltip = `title='Favorable Matchup: ${switchNote}Wind blowing out to Right Field (${windSpeed}mph)'`;
                } else if (isWindOutToLeft && effectiveBatSide === 'R') {
                    itemStyle = "color: #198754;";
                    tooltip = `title='Favorable Matchup: ${switchNote}Wind blowing out to Left Field (${windSpeed}mph)'`;
                } else if (isWindInFromRight && effectiveBatSide === 'L') {
                    itemStyle = "color: #dc3545;"; 
                    tooltip = `title='Unfavorable Matchup: ${switchNote}Wind blowing in from Right Field (${windSpeed}mph)'`;
                } else if (isWindInFromLeft && effectiveBatSide === 'R') {
                    itemStyle = "color: #dc3545;";
                    tooltip = `title='Unfavorable Matchup: ${switchNote}Wind blowing in from Left Field (${windSpeed}mph)'`;
                }
            }

            const handHtml = batCode ? `<span style="font-weight:normal; opacity:0.8; color: inherit;"> (${batCode})</span>` : "";
            return `<li ${tooltip} style="${itemStyle} cursor: default;">${formatPlayerName(p.fullName)}${handHtml}</li>`;
        }).join('');
        
        const collapseId = `lineup-home-${game.gamePk}`;
        homeLineupHtml = `
            <div class="mt-0 w-100"> 
                <a href="#${collapseId}" data-bs-toggle="collapse" aria-expanded="${ariaExpanded}" class="badge bg-primary text-white text-decoration-none" style="font-size: 0.65rem;">📋 View Lineup</a>
                <div class="${collapseClass} mt-1 text-start bg-light rounded p-1 border w-100" id="${collapseId}">
                    <ol class="mb-0 pe-0 text-muted w-100" style="padding-left: 1.1rem; font-size: 0.65rem; line-height: 1.3;">${list}</ol>
                </div>
            </div>`;
    }

    // --- 4. BETTING ODDS UI (IN HEADER) ---
    const oddsData = data.odds; 
    
    let mlAway = `<div class="fw-bold text-muted mt-1" style="font-size: 0.8rem;">TBD</div>`; 
    let mlHome = `<div class="fw-bold text-muted mt-1" style="font-size: 0.8rem;">TBD</div>`;
    let totalHtml = `
        <div class="d-flex flex-column justify-content-center align-items-center pt-2">
            <div class="text-muted small fw-bold mb-1">@</div>
            <div class="fw-bold text-muted" style="font-size: 0.8rem; letter-spacing: 0.5px;">O/U TBD</div>
        </div>`;

    if (oddsData && oddsData.bookmakers && oddsData.bookmakers.length > 0) {
        const bookie = oddsData.bookmakers.find(b => b.key === 'fanduel') || oddsData.bookmakers[0];
        
        const h2hMarket = bookie.markets.find(m => m.key === 'h2h');
        if (h2hMarket) {
            const awayOutcome = h2hMarket.outcomes.find(o => o.name === awayName);
            const homeOutcome = h2hMarket.outcomes.find(o => o.name === homeName);
            
            if (awayOutcome) {
                const price = awayOutcome.price > 0 ? `+${awayOutcome.price}` : awayOutcome.price;
                mlAway = `<div class="fw-bold text-dark mt-1" style="font-size: 0.8rem;">${price}</div>`;
            }
            if (homeOutcome) {
                const price = homeOutcome.price > 0 ? `+${homeOutcome.price}` : homeOutcome.price;
                mlHome = `<div class="fw-bold text-dark mt-1" style="font-size: 0.8rem;">${price}</div>`;
            }
        }

        const totalsMarket = bookie.markets.find(m => m.key === 'totals');
        if (totalsMarket && totalsMarket.outcomes.length > 0) {
            const gameTotal = totalsMarket.outcomes[0].point; 
            totalHtml = `
                <div class="d-flex flex-column justify-content-center align-items-center pt-2">
                    <div class="text-muted small fw-bold mb-1">@</div>
                    <div class="fw-bold text-dark" style="font-size: 0.8rem; letter-spacing: 0.5px;">O/U ${gameTotal}</div>
                </div>`;
        }
    }

    // --- 5. WEATHER & HOURLY DISPLAY ---
    let weatherHtml = `<div class="text-muted p-3 text-center small">Weather data unavailable.<br><span class="badge bg-light text-dark">Venue ID: ${game.venue.id}</span></div>`;

    if (stadium && weather) {
        if (weather.status === "too_early") {
            weatherHtml = `
                <div class="text-center p-3">
                    <h6 class="text-muted mb-1">🔭 Too Early to Forecast</h6>
                    <p class="small text-muted mb-0" style="font-size: 0.75rem;">Forecasts available ~14 days out.</p>
                </div>`;
        } else if (weather.temp !== '--') {
            const analysisText = generateMatchupAnalysis(weather, windInfo, isRoofClosed);
            
            let displayRain = isRoofClosed ? "0%" : `${weather.maxPrecipChance}%`;
            let precipLabel = "Rain"; 

            if (!isRoofClosed) {
                if (weather.isThunderstorm) displayRain += " ⚡";
                else if (weather.isSnow) { displayRain += " ❄️"; precipLabel = "Snow"; }
            }
            
            const radarUrl = `https://embed.windy.com/embed2.html?lat=${stadium.lat}&lon=${stadium.lon}&detailLat=${stadium.lat}&detailLon=${stadium.lon}&width=650&height=450&zoom=11&level=surface&overlay=rain&product=ecmwf&menu=&message=&marker=&calendar=now&pressure=&type=map&location=coordinates&detail=&metricWind=mph&metricTemp=%C2%B0F&radarRange=-1`;

            let hourlyHtml = '';
            if (isRoofClosed) {
                hourlyHtml = `<div class="text-center mt-2"><small class="text-muted">Indoor Conditions</small></div>`;
            } else if (weather.hourly && weather.hourly.length > 0) {
                const cardsHtml = weather.hourly.map((h, index) => {
                    const ampm = h.hour >= 12 ? 'PM' : 'AM';
                    const hour12 = h.hour % 12 || 12;
                    const timeLabel = `${hour12}${ampm}`;

                    let icon = '';
                    let popHtml = '&nbsp;'; 
                    const isNight = h.hour >= 20 || h.hour < 6;

                    if (h.precipChance >= 30) {
                        if (h.isThunderstorm) icon = '⛈️';
                        else if (h.isSnow) icon = '🌨️';
                        else icon = '🌧️';
                        popHtml = `${h.precipChance}%`;
                    } else if (h.precipChance > 0) {
                        icon = '⛅'; 
                        popHtml = `${h.precipChance}%`;
                    } else {
                        icon = isNight ? '🌙' : '☀️';
                    }
                    const tempDisplay = h.temp !== undefined ? `${h.temp}°` : '--';

                    return `
                        <div class="hour-card">
                            <div class="hour-time">${timeLabel}</div>
                            <div class="hour-icon">${icon}</div>
                            <div class="hour-pop">${popHtml}</div>
                            <div class="hour-temp">${tempDisplay}</div>
                        </div>`;
                }).join('');
                hourlyHtml = `<div class="hourly-scroll-container">${cardsHtml}</div>`;
            }
            
            const gameDataSafe = encodeURIComponent(JSON.stringify(data));

            weatherHtml = `
                <div class="weather-row row text-center align-items-center">
                    <div class="col-3 border-end px-1">
                        <div class="fw-bold">${weather.temp}°F</div>
                        <div class="small text-muted" style="font-size: 0.7rem;">Temp</div>
                    </div>
                    <div class="col-3 border-end px-1">
                        <div class="fw-bold text-dark">${weather.humidity}%</div>
                        <div class="small text-muted" style="font-size: 0.7rem;">Hum</div>
                    </div>
                    <div class="col-3 border-end px-1">
                        <div class="fw-bold text-primary" style="white-space: nowrap;">${displayRain}</div>
                        <div class="small text-muted" style="font-size: 0.7rem;">${precipLabel}</div>
                    </div>
                    <div class="col-3 px-1">
                        <div class="fw-bold">${weather.windSpeed} <span style="font-size:0.7em">mph</span></div>
                        <span class="wind-badge ${windInfo.cssClass}" style="font-size: 0.55rem; white-space: nowrap; display: inline-block; padding: 2px 4px;">
                            ${windInfo.arrow}
                        </span>
                    </div>
                </div>
                ${hourlyHtml}
                
                <div class="mt-2">
                    <button class="btn btn-sm btn-outline-primary w-100 py-1" onclick="showRadar('${radarUrl}', '${game.venue.name}')">
                        🗺️ View Live Radar
                    </button>
                </div>

                <div class="analysis-box">
                    <span class="analysis-title">✨ Weather Impact</span>
                    ${analysisText}
                </div>`;
        }
    }

   // --- MAIN CARD HTML GENERATION ---
    gameCard.innerHTML = `
        <div class="card game-card h-100 ${borderClass} ${bgClass}">
            <div class="card-body p-3 pb-2"> 
                <div class="d-flex justify-content-between align-items-center mb-2">
                    <span class="badge bg-light text-dark border">${gameTime}</span>
                    <span class="stadium-name text-truncate" style="max-width: 180px;">${game.venue.name}</span>
                </div>
                
                <div class="d-flex justify-content-between align-items-start px-1">
                    <div class="text-center" style="width: 45%; min-width: 0;"> 
                        <img src="${awayLogo}" alt="${awayName}" class="team-logo mb-1" onerror="this.style.display='none'">
                        <div class="d-flex flex-column justify-content-center align-items-center w-100">
                            <div class="fw-bold lh-sm text-dark text-truncate w-100" style="font-size: 0.9rem; letter-spacing: -0.3px;">${awayShortName}</div>
                            ${mlAway}
                        </div>
                        <div class="text-muted mt-1 mb-0 text-truncate w-100" style="font-size: 0.7rem;">${awayPitcher}</div>
                    </div>
                    
                    <div class="text-center" style="width: 10%; min-width: 0;">
                        ${totalHtml}
                    </div>
                    
                    <div class="text-center" style="width: 45%; min-width: 0;"> 
                        <img src="${homeLogo}" alt="${homeName}" class="team-logo mb-1" onerror="this.style.display='none'">
                        <div class="d-flex flex-column justify-content-center align-items-center w-100">
                            <div class="fw-bold lh-sm text-dark text-truncate w-100" style="font-size: 0.9rem; letter-spacing: -0.3px;">${homeShortName}</div>
                            ${mlHome}
                        </div>
                        <div class="text-muted mt-1 mb-0 text-truncate w-100" style="font-size: 0.7rem;">${homePitcher}</div>
                    </div>
                </div>
                
                <div class="row g-1 mt-0 mx-0">
                    <div class="col-6 px-1 text-center w-50">
                        ${awayLineupHtml}
                    </div>
                    <div class="col-6 px-1 text-center w-50">
                        ${homeLineupHtml}
                    </div>
                </div>
                
                ${weatherHtml}
            </div>
        </div>`;
    
    return gameCard;
}
// ==========================================
// 3. LISTENERS
// ==========================================

document.addEventListener('DOMContentLoaded', () => {
    init(DEFAULT_DATE);

    const searchInput = document.getElementById('team-search');
    const sortSelect = document.getElementById('sort-filter');
    const riskToggle = document.getElementById('risk-only');
    const lineupsToggle = document.getElementById('show-lineups');
    
    if(searchInput) searchInput.addEventListener('input', renderGames);
    if(sortSelect) sortSelect.addEventListener('change', renderGames);
    if(riskToggle) riskToggle.addEventListener('change', renderGames);
    if(lineupsToggle) lineupsToggle.addEventListener('change', renderGames);

    const datePicker = document.getElementById('date-picker');
    
    if (datePicker) {
        datePicker.value = DEFAULT_DATE;
        datePicker.addEventListener('change', (e) => {
            if (e.target.value) {
                e.target.blur(); 
                
                const riskToggle = document.getElementById('risk-only');
                if (riskToggle) riskToggle.checked = false;

                init(e.target.value);
            }
        });
    }
    
    const radarModal = document.getElementById('radarModal');
    if (radarModal) {
        radarModal.addEventListener('hidden.bs.modal', () => {
            const iframe = document.getElementById('radarFrame');
            if (iframe) iframe.src = ''; 
        });
    }
});

// ==========================================
// 4. HELPER FUNCTIONS
// ==========================================
function getWindArrowEmoji(direction) {
    if (direction === null || direction === undefined) return "💨";

    if (typeof direction === 'number') {
        const val = Math.floor((direction / 22.5) + 0.5);
        const arr = ["N", "NNE", "NE", "ENE", "E", "ESE", "SE", "SSE", "S", "SSW", "SW", "WSW", "W", "WNW", "NW", "NNW"];
        direction = arr[(val % 16)];
    }

    const map = {
        "N": "⬇️",   "NNE": "⬇️", "NE": "↙️",  "ENE": "↙️", 
        "E": "⬅️",   "ESE": "⬅️", "SE": "↖️",  "SSE": "↖️", 
        "S": "⬆️",   "SSW": "⬆️", "SW": "↗️",  "WSW": "↗️", 
        "W": "➡️",   "WNW": "➡️", "NW": "↘️",  "NNW": "↘️"  
    };

    return map[direction.toUpperCase()] || "💨";
}

function getTeamAbbr(teamName) {
    const map = {
        "Yankees": "NYY", "Mets": "NYM",
        "Cubs": "CHC", "White Sox": "CWS",
        "Dodgers": "LAD", "Angels": "LAA",
        "Diamondbacks": "ARI", "Braves": "ATL", "Orioles": "BAL", "Red Sox": "BOS",
        "Reds": "CIN", "Guardians": "CLE", "Rockies": "COL", "Tigers": "DET",
        "Astros": "HOU", "Royals": "KC",  "Marlins": "MIA", "Brewers": "MIL",
        "Twins": "MIN", "Athletics": "OAK", "Phillies": "PHI", "Pirates": "PIT",
        "Padres": "SD",  "Giants": "SF",  "Mariners": "SEA", "Cardinals": "STL",
        "Rays": "TB",   "Rangers": "TEX", "Blue Jays": "TOR", "Nationals": "WSH"
    };

    const key = Object.keys(map).find(k => teamName.includes(k));
    return key ? map[key] : "MLB"; 
}

// --- NEW HELPER: Formats names to "F. Lastname" ---
function formatPlayerName(fullName) {
    if (!fullName) return "";
    const parts = fullName.split(" ");
    if (parts.length === 1) return fullName; 
    
    const firstInitial = parts[0].charAt(0);
    const lastName = parts.slice(1).join(" ");
    return `${firstInitial}. ${lastName}`;
}

// --- NEW HELPER: Strips city name from Team Name safely ---
function getShortTeamName(fullName) {
    if (!fullName) return "";
    
    // Handle multi-word team names that break the "last word" rule
    if (fullName.includes("Red Sox")) return "Red Sox";
    if (fullName.includes("White Sox")) return "White Sox";
    if (fullName.includes("Blue Jays")) return "Blue Jays";
    
    // Otherwise, just return the final word (e.g., "Diamondbacks", "Angels")
    const parts = fullName.split(" ");
    return parts[parts.length - 1];
}

window.showRadar = function(url, venueName) {
    const modalElement = document.getElementById('radarModal');
    const modalTitle = document.querySelector('#radarModal .modal-title');
    const iframe = document.getElementById('radarFrame');
    
    if(modalTitle) modalTitle.innerText = `Radar: ${venueName}`;

    const myModal = bootstrap.Modal.getOrCreateInstance(modalElement);

    if(iframe) iframe.src = '';

    const loadMap = function () {
        if(iframe) iframe.src = url; 
        modalElement.removeEventListener('shown.bs.modal', loadMap); 
    };

    modalElement.addEventListener('shown.bs.modal', loadMap);
    myModal.show();
}

function generateMatchupAnalysis(weather, windInfo, isRoofClosed) {
    if (isRoofClosed) return "Roof closed. Controlled environment with zero weather impact.";

    let notes = [];

    if (weather.isThunderstorm) {
        notes.push("⚡ <b>Lightning Risk:</b> Thunderstorms detected. Mandatory 30-minute safety delays are likely.");
    }
    if (weather.isSnow) {
        notes.push("❄️ <b>Snow Risk:</b> Low visibility and slippery field conditions could delay play.");
    }

    let sustainedRainHours = 0;
    if (weather.hourly && weather.hourly.length > 0) {
        sustainedRainHours = weather.hourly.filter(h => h.precipChance >= 60).length;
    }

    if (sustainedRainHours >= 3) {
        notes.push("🌧️ <b>Rainout Risk:</b> Sustained heavy rain. High probability of postponement.");
    } else if (weather.maxPrecipChance >= 70) {
        notes.push("☔ <b>Severe Delay Risk:</b> Heavy rain expected, but should pass. Delays likely.");
    } else if (weather.maxPrecipChance >= 30) {
        notes.push("☔ <b>Delay Risk:</b> Scattered showers could interrupt play.");
    }

    if (weather.humidity <= 30) {
        notes.push("🌵 <b>Dry Air (<30%):</b> Sharp breaking balls (Pitcher Adv), but the ball travels up to 4.5ft farther (Hitter Adv).");
    } else if (weather.humidity >= 70) {
        notes.push("💧 <b>High Humidity (>70%):</b> Breaking balls hang/flatten (Hitter Adv), but the ball travels shorter distances (Pitcher Adv).");
    }

    if (weather.temp >= 85) {
        notes.push("🔥 <b>Hitter Friendly:</b> High temps reduce air density, helping fly balls carry.");
    } else if (weather.temp <= 50) {
        notes.push("❄️ <b>Pitcher Friendly:</b> Cold, dense air suppresses ball flight and scoring.");
    }

    if (weather.windSpeed >= 8) {
        const dir = windInfo.text;
        if (dir.includes("Blowing OUT")) notes.push("🚀 <b>Home Runs:</b> Strong wind blowing out creates ideal hitting conditions.");
        else if (dir.includes("Blowing IN")) notes.push("🛑 <b>Suppressed:</b> Wind blowing in will knock down fly balls. Advantage pitchers.");
        else if (dir.includes("Out to Right")) notes.push("↗️ <b>Lefty Advantage:</b> Wind blowing out to Right Field favors <b>Left-Handed</b> power.");
        else if (dir.includes("Out to Left")) notes.push("↖️ <b>Righty Advantage:</b> Wind blowing out to Left Field favors <b>Right-Handed</b> power.");
        else if (dir.includes("In from Right")) notes.push("📉 <b>Lefty Nightmare:</b> Wind blowing in from Right knocks down Lefty power.");
        else if (dir.includes("In from Left")) notes.push("📉 <b>Righty Nightmare:</b> Wind blowing in from Left knocks down Righty power.");
        else if (dir.includes("Cross")) notes.push("↔️ <b>Tricky:</b> Crosswinds may affect outfield defense and breaking balls.");
    }

    if (notes.length === 0) return "✅ <b>Neutral:</b> Fair weather conditions. No significant advantage.";
    return notes.join("<br>");
}

async function fetchGameWeather(lat, lon, gameDateIso) {
    const dateStr = gameDateIso.split('T')[0];
    
    const gameDateObj = new Date(gameDateIso);
    const nextDayObj = new Date(gameDateObj);
    nextDayObj.setUTCDate(nextDayObj.getUTCDate() + 1);
    const nextDateStr = nextDayObj.toISOString().split('T')[0];

    const today = new Date().toLocaleDateString('en-CA'); 
    const isHistorical = dateStr < today; 
    const daysDiff = (new Date(dateStr) - new Date(today)) / (1000 * 60 * 60 * 24);

    if (!isHistorical && daysDiff > 16) return { status: "too_early", temp: '--' };

    let url = "";
    
    if (isHistorical || dateStr === "2024-09-25") {
         url = `https://archive-api.open-meteo.com/v1/archive?latitude=${lat}&longitude=${lon}&start_date=${dateStr}&end_date=${nextDateStr}&hourly=temperature_2m,relative_humidity_2m,precipitation,weather_code,wind_speed_10m,wind_direction_10m&temperature_unit=fahrenheit&wind_speed_unit=mph&precipitation_unit=inch&timezone=GMT`;
    } 
    else if (daysDiff <= 3) {
         url = `https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&hourly=temperature_2m,relative_humidity_2m,precipitation_probability,precipitation,weather_code,wind_speed_10m,wind_direction_10m&temperature_unit=fahrenheit&wind_speed_unit=mph&precipitation_unit=inch&timezone=GMT&start_date=${dateStr}&end_date=${nextDateStr}`;
    }
    else {
         url = `https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&hourly=temperature_2m,relative_humidity_2m,precipitation_probability,precipitation,weather_code,wind_speed_10m,wind_direction_10m&models=gfs_seamless&temperature_unit=fahrenheit&wind_speed_unit=mph&precipitation_unit=inch&timezone=GMT&start_date=${dateStr}&end_date=${nextDateStr}`;
    }

    try {
        const response = await fetch(url);
        if (!response.ok) {
            if (response.status === 400) return { status: "too_early", temp: '--' };
            return { temp: '--', hourly: [] };
        }
        const data = await response.json();
        
        const gameHour = new Date(gameDateIso).getUTCHours();
        
        const normalizePrecip = (index) => {
            let prob = data.hourly.precipitation_probability ? data.hourly.precipitation_probability[index] || 0 : 0;
            let amount = data.hourly.precipitation ? data.hourly.precipitation[index] || 0 : 0;
            let code = data.hourly.weather_code[index];
            
            if (amount === 0 && code <= 3) {
                return 0; 
            }

            if (amount > 0) {
                if (amount >= 0.10) return Math.max(80, prob); 
                if (amount >= 0.05) return Math.max(60, prob); 
                if (amount >= 0.01) return Math.max(30, prob); 
                return 15; 
            }
            return prob;
        };

        const hourlySlice = [];
        let maxChanceInWindow = 0;
        let isGameThunderstorm = false;
        let isGameSnow = false; 

        for (let i = gameHour - 1; i <= gameHour + 3; i++) {
            if (i >= 0 && i < data.hourly.temperature_2m.length) {
                let chance = normalizePrecip(i);
                
                const code = data.hourly.weather_code[i];
                const isHourThunderstorm = (code >= 95 && code <= 99);
                const isHourSnow = (code === 71 || code === 73 || code === 75 || code === 77 || code === 85 || code === 86);

                if (isHourThunderstorm) isGameThunderstorm = true;
                if (isHourSnow) isGameSnow = true;

                if (i >= gameHour && i <= gameHour + 3 && chance > maxChanceInWindow) maxChanceInWindow = chance;
                
                let localHour = new Date(gameDateIso);
                localHour.setUTCHours(i);
                
                hourlySlice.push({ 
                    hour: localHour.getHours(), 
                    temp: Math.round(data.hourly.temperature_2m[i]), 
                    precipChance: chance,
                    isThunderstorm: isHourThunderstorm,
                    isSnow: isHourSnow 
                });
            }
        }

        return {
            status: "ok",
            temp: Math.round(data.hourly.temperature_2m[gameHour]),
            humidity: Math.round(data.hourly.relative_humidity_2m[gameHour]),
            maxPrecipChance: maxChanceInWindow, 
            isThunderstorm: isGameThunderstorm,
            isSnow: isGameSnow, 
            windSpeed: Math.round(data.hourly.wind_speed_10m[gameHour]),
            windDir: data.hourly.wind_direction_10m[gameHour],
            hourly: hourlySlice
        };
    } catch (e) {
        console.error("⚠️ Weather fetch failed:", e);
        return { temp: '--', hourly: [] };
    }
}

function calculateWind(windDirection, stadiumBearing) {
    let diff = (windDirection - stadiumBearing + 360) % 360;
    if (diff >= 337.5 || diff < 22.5) return { text: "Blowing IN", cssClass: "bg-in", arrow: "⬇" };
    if (diff >= 22.5 && diff < 67.5) return { text: "In from Right", cssClass: "bg-in", arrow: "↙" };
    if (diff >= 67.5 && diff < 112.5) return { text: "Cross (R to L)", cssClass: "bg-cross", arrow: "⬅" };
    if (diff >= 112.5 && diff < 157.5) return { text: "Out to Left", cssClass: "bg-out", arrow: "↖" };
    if (diff >= 157.5 && diff < 202.5) return { text: "Blowing OUT", cssClass: "bg-out", arrow: "⬆" };
    if (diff >= 202.5 && diff < 247.5) return { text: "Out to Right", cssClass: "bg-out", arrow: "↗" };
    if (diff >= 247.5 && diff < 292.5) return { text: "Cross (L to R)", cssClass: "bg-cross", arrow: "➡" };
    return { text: "In from Left", cssClass: "bg-in", arrow: "↘" };
}

function generateDailyReport() {
    if (ALL_GAMES_DATA.length === 0) {
        alert("No games data available to report!");
        return;
    }

    const sortedGames = [...ALL_GAMES_DATA].sort((a, b) => 
        new Date(a.gameRaw.gameDate) - new Date(b.gameRaw.gameDate)
    );

    const today = new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
    
    let reportText = `⚾ MLB Weather & Pitching Matchups • ${today}\n\n`; 

    sortedGames.forEach(game => {
        const teams = game.gameRaw.teams;
        const w = game.weather || {}; 
        
        const awayAbbr = getTeamAbbr(teams.away.team.name);
        const homeAbbr = getTeamAbbr(teams.home.team.name);
        
        const awayP = teams.away.probablePitcher ? teams.away.probablePitcher.fullName.split(' ').pop() : "TBD";
        const homeP = teams.home.probablePitcher ? teams.home.probablePitcher.fullName.split(' ').pop() : "TBD";
        
        let arrow = "💨";
        if (game.wind && game.wind.arrow) {
             arrow = game.wind.arrow;
        } else if (game.windDirection !== undefined) {
             arrow = getWindArrowEmoji(game.windDirection);
        }

        const isRoofClosed = game.roof;
        const rain = isRoofClosed ? 0 : Math.round(Number(w.maxPrecipChance) || 0);
        const temp = Math.round(Number(w.temp) || 0);
        const hum = Math.round(Number(w.humidity) || 0);
        const windSpd = isRoofClosed ? 0 : Math.round(Number(w.windSpeed) || 0);

        let weatherString = `🌧️${rain}% 🌡️${temp}° 💧${hum}% ${arrow}${windSpd}mph`;
        
        if (w.status === "too_early" || w.temp === '--') {
            weatherString = `Forecast Unavailable`;
        } else if (isRoofClosed) {
            weatherString = `Roof Closed 🌡️${temp}° 💧${hum}%`;
        }

        const line = `${awayAbbr} (${awayP}) @ ${homeAbbr} (${homeP}): ${weatherString}`;
        reportText += line + "\n";
    });

    reportText += `\nDetailed wind & lineup data: https://weathermlb.com\n#MLB #FantasyBaseball`;

    const textArea = document.getElementById('tweet-text');
    const twitterLink = document.getElementById('twitter-link');
    
    if (textArea) {
        textArea.value = reportText;

        if (twitterLink) {
            const twitterUrl = `https://twitter.com/intent/tweet?text=${encodeURIComponent(reportText)}`;
            twitterLink.href = twitterUrl;
        }
        
        const modalElement = document.getElementById('tweetModal');
        if (modalElement && typeof bootstrap !== 'undefined') {
            const modal = new bootstrap.Modal(modalElement);
            modal.show();
        } else {
             alert("Report generated:\n\n" + reportText);
        }
    }
}
